<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Manipulando os dados no RStudio – Bioestatística Usando o R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06-descrevendoDados.html" rel="next">
<link href="./04-ambienteR.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-8da5b4427184b79ecddefad3d342027e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-manipulandoDados.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Manipulando os dados no <em>RStudio</em></span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Procurar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Bioestatística Usando o R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Procurar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefácio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introdução</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-dados.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Natureza dos Dados</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-producaoDados.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Produção dos Dados</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-ambienteR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Ambiente do <em>R</em></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-manipulandoDados.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Manipulando os dados no <em>RStudio</em></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-descrevendoDados.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Descrevendo os dados</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-probabilidades.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Introdução à Teoria das Probabilidades</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-assimetria_curtose.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Assimetria e Curtose</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-distAmostrais.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Distribuições Amostrais</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-estimacao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Estimação</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-testeHipoteses.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Teste de Hipóteses</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-teste-t.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Comparação entre duas médias</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Análise de Variância</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#importando-dados-de-outros-softwares" id="toc-importando-dados-de-outros-softwares" class="nav-link active" data-scroll-target="#importando-dados-de-outros-softwares"><span class="header-section-number">5.1</span> Importando dados de outros <em>softwares</em></a>
  <ul class="collapse">
  <li><a href="#sec-csv" id="toc-sec-csv" class="nav-link" data-scroll-target="#sec-csv"><span class="header-section-number">5.1.1</span> Importando dados de um arquivo CSV</a></li>
  <li><a href="#sec-xlsx" id="toc-sec-xlsx" class="nav-link" data-scroll-target="#sec-xlsx"><span class="header-section-number">5.1.2</span> Importando um arquivo do Excel</a></li>
  <li><a href="#importando-arquivos-com-o-rstudio" id="toc-importando-arquivos-com-o-rstudio" class="nav-link" data-scroll-target="#importando-arquivos-com-o-rstudio"><span class="header-section-number">5.1.3</span> Importando arquivos com o RStudio</a></li>
  </ul></li>
  <li><a href="#sec-tibble" id="toc-sec-tibble" class="nav-link" data-scroll-target="#sec-tibble"><span class="header-section-number">5.2</span> Tibble</a></li>
  <li><a href="#sec-mater" id="toc-sec-mater" class="nav-link" data-scroll-target="#sec-mater"><span class="header-section-number">5.3</span> Pacote <code>dplyr</code></a>
  <ul class="collapse">
  <li><a href="#função-select" id="toc-função-select" class="nav-link" data-scroll-target="#função-select"><span class="header-section-number">5.3.1</span> Função <code>select()</code></a></li>
  <li><a href="#função-filter" id="toc-função-filter" class="nav-link" data-scroll-target="#função-filter"><span class="header-section-number">5.3.2</span> Função <code>filter()</code></a></li>
  <li><a href="#sec-mutate" id="toc-sec-mutate" class="nav-link" data-scroll-target="#sec-mutate"><span class="header-section-number">5.3.3</span> Função <code>mutate()</code></a></li>
  <li><a href="#função-sample_n" id="toc-função-sample_n" class="nav-link" data-scroll-target="#função-sample_n"><span class="header-section-number">5.3.4</span> Função <code>sample_n()</code></a></li>
  <li><a href="#função-slice" id="toc-função-slice" class="nav-link" data-scroll-target="#função-slice"><span class="header-section-number">5.3.5</span> Função <code>slice()</code></a></li>
  <li><a href="#função-arrange" id="toc-função-arrange" class="nav-link" data-scroll-target="#função-arrange"><span class="header-section-number">5.3.6</span> Função <code>arrange()</code></a></li>
  <li><a href="#função-count" id="toc-função-count" class="nav-link" data-scroll-target="#função-count"><span class="header-section-number">5.3.7</span> Função <code>count()</code></a></li>
  <li><a href="#operador-pipe" id="toc-operador-pipe" class="nav-link" data-scroll-target="#operador-pipe"><span class="header-section-number">5.3.8</span> Operador pipe %&gt;%</a></li>
  </ul></li>
  <li><a href="#manipulação-de-datas" id="toc-manipulação-de-datas" class="nav-link" data-scroll-target="#manipulação-de-datas"><span class="header-section-number">5.4</span> Manipulação de datas</a>
  <ul class="collapse">
  <li><a href="#convertendo-strings-ou-caractere-para-data" id="toc-convertendo-strings-ou-caractere-para-data" class="nav-link" data-scroll-target="#convertendo-strings-ou-caractere-para-data"><span class="header-section-number">5.4.1</span> Convertendo <em>strings</em> ou caractere para data</a></li>
  <li><a href="#juntando-componentes-de-datas" id="toc-juntando-componentes-de-datas" class="nav-link" data-scroll-target="#juntando-componentes-de-datas"><span class="header-section-number">5.4.2</span> Juntando componentes de datas</a></li>
  <li><a href="#extraindo-componentes-de-datas" id="toc-extraindo-componentes-de-datas" class="nav-link" data-scroll-target="#extraindo-componentes-de-datas"><span class="header-section-number">5.4.3</span> Extraindo componentes de datas</a></li>
  <li><a href="#operações-com-datas" id="toc-operações-com-datas" class="nav-link" data-scroll-target="#operações-com-datas"><span class="header-section-number">5.4.4</span> Operações com datas</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Manipulando os dados no <em>RStudio</em></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="importando-dados-de-outros-softwares" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="importando-dados-de-outros-softwares"><span class="header-section-number">5.1</span> Importando dados de outros <em>softwares</em></h2>
<p>É possível inserir dados diretamente no <em>R Script</em>, como mostrado na <a href="04-ambienteR.html#sec-dataframes" class="quarto-xref"><span>Seção 4.11</span></a>. Entretanto, se o conjunto de dados for muito extenso, torna-se complicado. Desta forma, é melhor importar os dados de outro software, como o Excel, SPSS, etc. A recomendação é que se construa o banco de dados, por exemplo, no <em>Excel</em>, e, depois, exporte o arquivo em um formato que o <em>R</em> reconheça – <code>.xlsx</code>, <code>.csv</code>, <code>.sav</code>.</p>
<section id="sec-csv" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="sec-csv"><span class="header-section-number">5.1.1</span> Importando dados de um arquivo CSV</h3>
<p>O formato CSV significa <em>Comma Separated Values</em>, ou seja, é um arquivo de valores separados por vírgula. Esse formato de armazenamento é simples e agrupa informações de arquivos de texto em planilhas. É possível gerar um arquivo <code>.csv</code>, a partir de uma planilha do <em>Excel</em>, usando o menu <code>salvar como</code> e escolher <code>CSV</code>.</p>
<p>As funções <code>read.csv()</code> e <code>read.csv2()</code>, incluídas no <em>R</em> base, podem ser utilizadas para importar arquivos CSV. Existe uma pequena diferença entre elas. Dois argumentos dessas funções têm padrão diferentes em cada uma. São eles: <code>sep</code> (separador de colunas) e <code>dec</code> (separador de decimais). Na <code>read.csv()</code>, o padrão é <code>sep = ”,”</code> e <code>dec = ”.”</code> e em <code>read.csv2()</code> o padrão é <code>sep = “;”</code> e <code>dec = ”,”</code>. Portanto, quando se importa um arquivo <code>.csv</code>, é importante saber qual a sua estrutura. Verificar se os decimais estão separados por <em>ponto</em> ou por <em>vírgula</em> e se as colunas (variáveis), por <em>vírgula</em> ou <em>ponto e vírgula</em>. Para ver isso, basta abrir o arquivo em um bloco de notas (por exemplo, <em>Bloco de Notas do Windows</em>, <em>Notepad ++</em>).</p>
<p>Quando se usa o <code>read.csv()</code> há necessidade de informar o separador e o decimal, pois senão ele usará o padrão inglês e o arquivo não será lido. Já com <code>read.csv2()</code>, que usa o padrão brasileiro, não há necessidade de informar ao <em>R</em> qual o separador de colunas e nem o separador dos decimais.</p>
<p>Além disso, é necessário saber em que diretório do computador está o arquivo para informar ao comando. Recomenda-se colocar o arquivo na pasta do diretório de trabalho, pois assim basta apenas colocar o nome do arquivo na função de leitura dos dados. Caso contrário, tem-se que se usar todo o caminho (<em>path</em>).</p>
<p>Como exemplo, será importado o arquivo <code>dadosNeonatos.csv</code> que se encontra no diretório de trabalho do autor, salvo anteriormente. Para obter o arquivo, clique <a href="https://github.com/petronioliveira/Arquivos/blob/main/dadosNeonatos.csv"><strong>aqui</strong></a> e salve em seu diretório de trabalho.</p>
<p>A estrutura deste arquivo mostra que as colunas estão separadas por ponto-e-virgula e, portanto, a leitura dos dados será feita com a função <code>read.csv2()</code> e, como o arquivo está no diretório de trabalho, não há necessidade de informar o diretório completo. Os dados serão colocados em um objeto de nome <code>neonatos</code> <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>neonatos <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">"./dados/dadosNeonatos.csv"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Use a função <code>str()</code> para visualizar o conjunto de dados:<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(neonatos)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   15 obs. of  7 variables:
 $ id       : int  1 2 3 4 5 6 7 8 9 10 ...
 $ pesoRN   : int  3340 3345 3750 3650 3220 4070 3380 3970 3060 3180 ...
 $ compRN   : int  50 48 52 48 50 51 50 51 47 47 ...
 $ sexo     : chr  "F" "F" "F" "M" ...
 $ tipoParto: chr  "normal" "normal" "cesareo" "normal" ...
 $ idadeMae : int  40 19 26 19 32 24 27 20 21 19 ...
 $ utiNeo   : chr  "não" "não" "não" "não" ...</code></pre>
</div>
</div>
<p>Recentemente, foi desenvolvido o pacote <code>readr</code>, incluído no conjunto de pacotes <code>tidyverse</code> <span class="citation" data-cites="wickham2019tidyverse">(<a href="references.html#ref-wickham2019tidyverse" role="doc-biblioref">1</a>)</span>, para lidar rapidamente com a leitura de grandes arquivos. O pacote fornece substituições para funções como <code>read.csv()</code>. As funções <code>read_csv()</code> e <code>read_csv2()</code> oferecidas pelo <code>readr</code> são análogas às do <em>R</em> base. Entretanto, são muito mais rápidas e fornecem mais recursos, como um método compacto para especificar tipos de coluna. Além disso, produzem <code>tibbles</code> (ver adiante, <a href="#sec-tibble" class="quarto-xref"><span>Seção 5.2</span></a>) que são mais reproduzíveis, pois as funções básicas do R herdam alguns comportamentos do sistema operacional e das variáveis de ambiente, portanto, o código de importação que funciona no seu computador pode não funcionar no de outra pessoa. Para usar a função é necessário instalar e ativar o pacote <code>readr</code>. A função <code>read_csv2()</code> será utilizada para criar um outro objeto de nome <code>recemNascidos</code>, mas o conjunto de dados a ser ativado é o mesmo (<code>dadosNeonatos</code>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">library</span>(readr)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a> recemNascidos <span class="ot">&lt;-</span> <span class="fu">read_csv2</span>(<span class="st">"dados/dadosNeonatos.csv"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>ℹ Using "','" as decimal and "'.'" as grouping mark. Use `read_delim()` for more control.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 15 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ";"
chr (3): sexo, tipoParto, utiNeo
dbl (4): id, pesoRN, compRN, idadeMae

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p>Quando você executa <code>read_csv2()</code>, ele imprime uma especificação de coluna que fornece o nome e o tipo de cada coluna.</p>
<p>Novamente, a função <code>str()</code> mostrará a estrutura do arquivo <a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(recemNascidos)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [15 × 7] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ id       : num [1:15] 1 2 3 4 5 6 7 8 9 10 ...
 $ pesoRN   : num [1:15] 3340 3345 3750 3650 3220 ...
 $ compRN   : num [1:15] 50 48 52 48 50 51 50 51 47 47 ...
 $ sexo     : chr [1:15] "F" "F" "F" "M" ...
 $ tipoParto: chr [1:15] "normal" "normal" "cesareo" "normal" ...
 $ idadeMae : num [1:15] 40 19 26 19 32 24 27 20 21 19 ...
 $ utiNeo   : chr [1:15] "não" "não" "não" "não" ...
 - attr(*, "spec")=
  .. cols(
  ..   id = col_double(),
  ..   pesoRN = col_double(),
  ..   compRN = col_double(),
  ..   sexo = col_character(),
  ..   tipoParto = col_character(),
  ..   idadeMae = col_double(),
  ..   utiNeo = col_character()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
</div>
</section>
<section id="sec-xlsx" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="sec-xlsx"><span class="header-section-number">5.1.2</span> Importando um arquivo do Excel</h3>
<p>O pacote <code>readxl</code>, pertencente ao conjunto de pacotes do <code>tidyverse</code>, facilita a obtenção de dados do Excel para o R, através da função <code>read_excel()</code>. esta função tem o argumento <code>sheet =</code> , que deve ser usado indicando o número ou o nome da planilha, colocado entre aspas. Este argumento é importante se houver mais de uma planilha, caso contrário, ele é opcional. Para saber os outros argumentos da função, colque o cursor dentro da função e aperte a tecla <code>Tab</code> (<a href="#fig-sheet" class="quarto-xref">Figura&nbsp;<span>5.1</span></a>). Isto abrirá um menu com os argumentos:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-sheet" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-pos="H" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sheet-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="https://i.imgur.com/5qY7z0C.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%" data-fig-pos="H">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sheet-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5.1: Argumentos da função para importar arquivos xlsx
</figcaption>
</figure>
</div>
</div>
</div>
<p>Será feita a leitura dos mesmos dados, usados na leitura de dados <code>csv</code>, apenas o arquivo agora está no formato <code>.xlsx</code>. Para obter o arquivo, siga os mesmos passos, usados anteriormente. Clique <a href="https://github.com/petronioliveira/Arquivos/blob/main/dadosNeonatos.xlsx"><strong>aqui</strong></a> e salve em seu diretório de trabalho.</p>
<p>Os dados serão atribuídos a um objeto com outro nome (<code>recemNatos</code>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>recemNatos <span class="ot">&lt;-</span> readxl<span class="sc">::</span><span class="fu">read_excel</span>(<span class="st">"dados/dadosNeonatos.xlsx"</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(recemNatos)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [15 × 7] (S3: tbl_df/tbl/data.frame)
 $ id       : num [1:15] 1 2 3 4 5 6 7 8 9 10 ...
 $ pesoRN   : num [1:15] 3340 3345 3750 3650 3220 ...
 $ compRN   : num [1:15] 50 48 52 48 50 51 50 51 47 47 ...
 $ sexo     : chr [1:15] "F" "F" "F" "M" ...
 $ tipoParto: chr [1:15] "normal" "normal" "cesareo" "normal" ...
 $ idadeMae : num [1:15] 40 19 26 19 32 24 27 20 21 19 ...
 $ utiNeo   : chr [1:15] "não" "não" "não" "não" ...</code></pre>
</div>
</div>
<p>Na <a href="#fig-sheet" class="quarto-xref">Figura&nbsp;<span>5.1</span></a>, o duplo dois pontos (<code>::</code>) precedido do nome do pacote, no caso <code>readxl</code>, especifica a procedência da função usada. Nesta situação, não há necessidade de usar a função <code>library()</code> para carregar o pacote já instalado em um diretório (biblioteca) previamente.</p>
</section>
<section id="importando-arquivos-com-o-rstudio" class="level3" data-number="5.1.3">
<h3 data-number="5.1.3" class="anchored" data-anchor-id="importando-arquivos-com-o-rstudio"><span class="header-section-number">5.1.3</span> Importando arquivos com o RStudio</h3>
<p>O <code>RStudio</code> permite importar arquivos sem a necessidade de digitar comandos, que, para alguns podem ser tediosos.</p>
<p>Na tela inicial do <code>RStudio</code>, à direita, na parte superior, clique na aba <em>Environment</em> e em <code>Import Dataset</code>. Esta ação abre um menu que permite importar arquivos .csv, Excel, SPSS, etc.</p>
<p>Por exemplo, para importar o arquivo <code>dadosNeonatos.xlsx</code>, clicar em <code>From Excel...</code> Abre uma janela com uma caixa de diálogo. Clicar no botão <code>Browse...</code>, localizado em cima à direita, para buscar o arquivo <code>dadosNeonatos.xlsx</code>. Assim que o arquivo for aberto, ele mostra uma <em>preview</em> do arquivo e, em baixo, à direita mostra uma <em>preview</em> do código (<a href="#fig-import" class="quarto-xref">Figura&nbsp;<span>5.2</span></a>)), igual ao digitado anteriormente, que cria um objeto denominado <code>dadosNeonatos</code>, nome do objeto escolhido pelo R, mas pode ser modificado na janela, à esquerda, <code>Import Option</code> em <code>Name</code>, onde pode-se digitar qualquer nome. Após encerrar as escolhas, clicar em <code>Import</code>. É um caminho diferente para fazer o mesmo. Este é um dos fascínios do R!</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-import" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-pos="H" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-import-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="https://i.imgur.com/xjEpK6A.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%" data-fig-pos="H">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-import-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5.2: Importando arquivos do excel com o RStudio.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="sec-tibble" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="sec-tibble"><span class="header-section-number">5.2</span> Tibble</h2>
<p>A maneira mais comum de armazenar dados no <em>R</em> é usar <code>data.frames</code> ou <code>tibble</code>.</p>
<p><em>Tibble</em> é um novo tipo de dataframe. É como se fosse um dataframe mais moderno. Ele mantém muitos recursos importantes do data frame original, mas remove muitos dos recursos desatualizados.</p>
<p>Os <code>tibbles</code> são outro recurso incrível adicionado ao <em>R</em> por Hadley Wickham, através do <code>tidyverse</code>, conjunto de pacotes que formam um conjunto básico de funções que facilitam a manipulação e representação gráfica dos dados <span class="citation" data-cites="wickham2019tidyverse">(<a href="references.html#ref-wickham2019tidyverse" role="doc-biblioref">1</a>)</span>. Para saber mais sobre <code>tibble</code>, veja vignette(‘tibbles’), em `help´.</p>
<p>A maioria dos pacotes do <em>R</em> usa dataframes tradicionais, entretanto é possível transformá-los para <code>tibble</code>, usando a função <code>as_tibble()</code>, incluída no pacote <code>tidyr</code> <span class="citation" data-cites="wickham2022tidyr">(<a href="references.html#ref-wickham2022tidyr" role="doc-biblioref">2</a>)</span>. O único propósito deste pacote é simplificar o processo de criação de <code>tidy data</code>(dados organizados).</p>
<p>O conceito de <em>tidy data</em>, introduzido por Wickman <span class="citation" data-cites="wickham2014tidy">(<a href="references.html#ref-wickham2014tidy" role="doc-biblioref">3</a>)</span>, se refere à estrutura dos dados organizados de maneira que cada linha é uma observação, cada coluna representa variáveis e cada entrada nas células do dataframe são os valores. A transformação de um dataframe tradicional em um <code>tibble</code>, é um procedimento rescomendável, em função da maior flexibilidade destes.</p>
<p>Como exemplo deste procedimento, será usado o famoso conjunto de dados da flor iris <span class="citation" data-cites="fisher1936use">(<a href="references.html#ref-fisher1936use" role="doc-biblioref">4</a>)</span> que fornece as medidas em centímetros das variáveis comprimento e largura da sepala e comprimento e largura da pétala, repectivamente, para 50 flores de cada uma das 3 espécies de íris (<em>Iris setosa</em>, <em>versicolor</em> e <em>virginica</em>). Este conjunto de dados encontra-se no pacote <code>datasets</code> no <em>R</em> base. Para visualizar os dados, será usado a função <code>str()</code>, também do <em>R</em> base, que mostra a estrutura interna de um objeto:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(iris)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
</div>
<p>Observa-se que é um conjunto de dados da classe <code>data.frame</code>, contendo 150 observações de 5 variáveis (colunas). Fazendo a coerção para um <code>tibble</code>, tem-se:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">as_tibble</span>(iris)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 150 × 5
   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
          &lt;dbl&gt;       &lt;dbl&gt;        &lt;dbl&gt;       &lt;dbl&gt; &lt;fct&gt;  
 1          5.1         3.5          1.4         0.2 setosa 
 2          4.9         3            1.4         0.2 setosa 
 3          4.7         3.2          1.3         0.2 setosa 
 4          4.6         3.1          1.5         0.2 setosa 
 5          5           3.6          1.4         0.2 setosa 
 6          5.4         3.9          1.7         0.4 setosa 
 7          4.6         3.4          1.4         0.3 setosa 
 8          5           3.4          1.5         0.2 setosa 
 9          4.4         2.9          1.4         0.2 setosa 
10          4.9         3.1          1.5         0.1 setosa 
# ℹ 140 more rows</code></pre>
</div>
</div>
<p>Verifica-se que não houve grandes mudanças, apenas o conjunto de dados está estruturalmente mais organizado, mais flexível.</p>
</section>
<section id="sec-mater" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="sec-mater"><span class="header-section-number">5.3</span> Pacote <code>dplyr</code></h2>
<p>O pacote <code>dpylr</code> é comumente usado para limpar e trabalhar com dados <span class="citation" data-cites="wickham2015dplyr">(<a href="references.html#ref-wickham2015dplyr" role="doc-biblioref">5</a>)</span>. No nível mais básico, as funções do pacote referem-se a “verbos” de manipulação de dados, como <code>select</code>, <code>filter</code>, <code>mutate</code>, <code>arrange</code>, <code>summarize</code>, entre outros, que permitem encadear várias etapas em algumas linhas de código, como será visto adiante.</p>
<p>O pacote <code>dplyr</code> é adequado para trabalhar com um único conjunto de dados, bem como para obter resultados complexos em grandes conjuntos de dados. As funções <code>dplyr</code> são processadas mais rápido do que as funções <em>R</em> base.</p>
<p>Para trabalhar na manipulação dos dados serão usados alguns pacotes, já mencionados anteriormente, <code>readxl</code> e <code>dplyr</code>, e o conjunto de dados <code>dadosMater.xlsx</code>. Para obter estes dados, clique <a href="https://github.com/petronioliveira/Arquivos/blob/main/dadosMater.xlsx"><strong>aqui</strong></a> e faça o download para o seu diretório de trabalho, como orientado anteriormente.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Anexando pacote: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Os seguintes objetos são mascarados por 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Os seguintes objetos são mascarados por 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>mater <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"dados/dadosMater.xlsx"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>A função <code>read_excel()</code> carrega o arquivo e o atribui a um objeto , arbitrariamente, denominado de <code>mater</code><a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as_tibble</span>(mater)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,368 × 30
      id idadeMae altura  peso ganhoPeso anosEst   cor eCivil renda  fumo
   &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1     1       42   1.65  69.9       3.9       3     2      1  1.45     2
 2     2       29   1.66  78        16.5      11     1      2  2.41     2
 3     3       19   1.72  81         5         9     2      1  1.93     2
 4     4       31   1.55  74        43         5     2      2  1.45     2
 5     5       34   1.6   60        15         7     2      2  0.48     2
 6     6       29   1.5   60        11.4       8     2      2  0.96     1
 7     7       30   1.54  75.5      10.5       4     1      2  1.2      1
 8     8       34   1.63  61         9         6     1      2  2.41     2
 9     9       17   1.68  57        15        10     1      2  2.17     2
10    10       32   1.5   70        11.4       1     2      2  0.72     2
# ℹ 1,358 more rows
# ℹ 20 more variables: quantFumo &lt;dbl&gt;, prenatal &lt;dbl&gt;, para &lt;dbl&gt;,
#   droga &lt;dbl&gt;, ig &lt;dbl&gt;, tipoParto &lt;dbl&gt;, pesoPla &lt;dbl&gt;, sexo &lt;dbl&gt;,
#   pesoRN &lt;dbl&gt;, compRN &lt;dbl&gt;, pcRN &lt;dbl&gt;, apgar1 &lt;dbl&gt;, apgar5 &lt;dbl&gt;,
#   utiNeo &lt;dbl&gt;, obito &lt;dbl&gt;, hiv &lt;dbl&gt;, sifilis &lt;dbl&gt;, rubeola &lt;dbl&gt;,
#   toxo &lt;dbl&gt;, infCong &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Por padrão, a função retorna as dez primeiras linhas. Além disso, colunas que não couberem na largura da tela serão omitidas. Também são apresentadas a dimensão da tabela e as classes de cada coluna. Observa-se que ele tem 1368 linhas (observações) e 30 colunas (variáveis). Além disso, verifica-se que todas as variáveis estão como numéricas (<code>dbl</code>) e, certamente, algumas, dependendo do objetivo na análise, precisarão ser transformadas.</p>
<p>O significado de cada uma das variáveis do arquivo <code>dadosMater.xlsx</code> <a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> é mostrado abaixo.</p>
<ul>
<li><strong>id</strong> <span class="math inline">\(\to\)</span> identificação do participante<br>
</li>
<li><strong>idadeMae</strong> <span class="math inline">\(\to\)</span> idade da parturiente em anos<br>
</li>
<li><strong>altura</strong> <span class="math inline">\(\to\)</span> altura da parturiente em metros<br>
</li>
<li><strong>peso</strong> <span class="math inline">\(\to\)</span> peso da parturiente em kg<br>
</li>
<li><strong>ganhoPeso</strong> <span class="math inline">\(\to\)</span> aumento de peso durante a gestação<br>
</li>
<li><strong>anosEst</strong> <span class="math inline">\(\to\)</span> anos de estudo completos<br>
</li>
<li><strong>cor</strong> <span class="math inline">\(\to\)</span> cor declarada pela parturiente: 1 = branca; 2 = não branca<br>
</li>
<li><strong>eCivil</strong> <span class="math inline">\(\to\)</span> estado civil: 1 = solteira; 2 = casada ou companheira<br>
</li>
<li><strong>renda</strong> <span class="math inline">\(\to\)</span> renda familiar em salários minimos<br>
</li>
<li><strong>fumo</strong> <span class="math inline">\(\to\)</span> tabagismo: 1 = sim; 2 = não<br>
</li>
<li><strong>quantFumo</strong> <span class="math inline">\(\to\)</span> quantidade de cigarros fumados diariamente<br>
</li>
<li><strong>prenatal</strong> <span class="math inline">\(\to\)</span> realizou pelo menos 6 consultas no pré-natal? 1 = sim; 2 = não</li>
<li><strong>para</strong> <span class="math inline">\(\to\)</span> número de filhos paridos<br>
</li>
<li><strong>droga</strong> <span class="math inline">\(\to\)</span> drogadição? 1 = sim; 2 = não<br>
</li>
<li><strong>ig</strong> <span class="math inline">\(\to\)</span> idade gestacional em semanas<br>
</li>
<li><strong>tipoParto</strong> <span class="math inline">\(\to\)</span> tipo de parto: 1 = normal; 2 = cesareana<br>
</li>
<li><strong>pesoPla</strong> <span class="math inline">\(\to\)</span> peso da placenta em gramas</li>
<li><strong>sexo</strong> <span class="math inline">\(\to\)</span> sexo do recém-nascido (RN): 1 = masc; 2 = fem<br>
</li>
<li><strong>pesoRN</strong> <span class="math inline">\(\to\)</span> peso do RN em gramas<br>
</li>
<li><strong>compRN</strong> <span class="math inline">\(\to\)</span> comprimento do RN em cm<br>
</li>
<li><strong>pcRN</strong> <span class="math inline">\(\to\)</span> perímetro cefálico dorecém-nascido em cm<br>
</li>
<li><strong>apgar1</strong> <span class="math inline">\(\to\)</span> escore de Apgar no primeiro minuto<br>
</li>
<li><strong>apgar5</strong> <span class="math inline">\(\to\)</span> escore de Apgar no quinto minuto<br>
</li>
<li><strong>utiNeo</strong> <span class="math inline">\(\to\)</span> RN necessitou de terapia intesiva? 1 = sim; 2 = não<br>
</li>
<li><strong>obito</strong> <span class="math inline">\(\to\)</span> obito no período neonatal? 1 = sim; 2 = não<br>
</li>
<li><strong>hiv</strong> <span class="math inline">\(\to\)</span> parturiente portadora de HIV? 1 = sim; 2 = não<br>
</li>
<li><strong>sifilis</strong> <span class="math inline">\(\to\)</span> parturiente portadora de sífilis? 1 = sim; 2 = não<br>
</li>
<li><strong>rubeola</strong> <span class="math inline">\(\to\)</span> parturiente portadora de rubéola? 1 = sim; 2 = não<br>
</li>
<li><strong>toxo</strong> <span class="math inline">\(\longrightarrow\)</span> parturiente portadora de toxoplasmose? 1 = sim; 2 = não<br>
</li>
<li><strong>infCong</strong> <span class="math inline">\(\to\)</span> parturiente portadora de alguma infecção congênita? 1 = sim; 2 = não</li>
</ul>
<section id="função-select" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="função-select"><span class="header-section-number">5.3.1</span> Função <code>select()</code></h3>
<p>A função <code>select ()</code> é usada para escolher quais colunas (variáveis) entrarão na análise. Ela recebe os nomes das colunas como argumentos e cria um novo banco de dados usando as colunas selecionadas. A função <code>select ()</code> pode ser combinada com outras funções, como <code>filter ()</code>.</p>
<p>Por exemplo, um novo banco de dados será criado (<code>mater1</code>), contendo as mesmas 1368 linhas, mas apenas com as variáveis <code>idadeMae</code>, <code>altura</code>, <code>peso</code>, <code>anosEst</code>, <code>renda</code>, <code>ig</code>, <code>fumo</code>, <code>pesoRN</code>, <code>sexo</code>. Consulte a ajuda (<code>?select()</code>) para obter maiores informações em relação aos argumentos da função:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>mater1 <span class="ot">&lt;-</span> <span class="fu">select</span>(mater, idadeMae, altura, peso, anosEst, renda, ig, tipoParto, fumo, pesoRN, sexo)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Para visualizar este novo banco de dados, pode-se usar a função <code>str()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mater1)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [1,368 × 10] (S3: tbl_df/tbl/data.frame)
 $ idadeMae : num [1:1368] 42 29 19 31 34 29 30 34 17 32 ...
 $ altura   : num [1:1368] 1.65 1.66 1.72 1.55 1.6 1.5 1.54 1.63 1.68 1.5 ...
 $ peso     : num [1:1368] 69.9 78 81 74 60 60 75.5 61 57 70 ...
 $ anosEst  : num [1:1368] 3 11 9 5 7 8 4 6 10 1 ...
 $ renda    : num [1:1368] 1.45 2.41 1.93 1.45 0.48 0.96 1.2 2.41 2.17 0.72 ...
 $ ig       : num [1:1368] 29 33 33 33 33 33 33 33 34 34 ...
 $ tipoParto: num [1:1368] 2 2 1 1 2 1 2 1 1 2 ...
 $ fumo     : num [1:1368] 2 2 2 2 2 1 1 2 2 2 ...
 $ pesoRN   : num [1:1368] 1035 2300 1580 1840 2475 ...
 $ sexo     : num [1:1368] 2 2 2 2 2 2 2 2 2 2 ...</code></pre>
</div>
</div>
<p>Como mostrado anteriormente, muitas variáveis numéricas do <code>mater</code>, na realidade, são fatores e necessitam de modificação. Entretanto, das selecionadas, para constituir o novo banco de dados, apenas <code>tipoParto</code>, <code>fumo</code> e <code>sexo</code> necessitam serem transformadas para fator:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>mater1<span class="sc">$</span>tipoParto <span class="ot">&lt;-</span> <span class="fu">factor</span>(mater1<span class="sc">$</span>tipoParto, </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>),</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"normal"</span>,<span class="st">"cesareo"</span>))</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>mater1<span class="sc">$</span>fumo <span class="ot">&lt;-</span> <span class="fu">factor</span> (mater1<span class="sc">$</span>fumo,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>                       <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), </span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>                       <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">'sim'</span>,<span class="st">'não'</span>))</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>mater1<span class="sc">$</span>sexo <span class="ot">&lt;-</span> <span class="fu">factor</span> (mater1<span class="sc">$</span>sexo, </span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>                       <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), </span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>                       <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"masc"</span>,<span class="st">"fem"</span>))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Usando, de novo, a função <code>str()</code>, é possível observar a transformação:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mater1)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [1,368 × 10] (S3: tbl_df/tbl/data.frame)
 $ idadeMae : num [1:1368] 42 29 19 31 34 29 30 34 17 32 ...
 $ altura   : num [1:1368] 1.65 1.66 1.72 1.55 1.6 1.5 1.54 1.63 1.68 1.5 ...
 $ peso     : num [1:1368] 69.9 78 81 74 60 60 75.5 61 57 70 ...
 $ anosEst  : num [1:1368] 3 11 9 5 7 8 4 6 10 1 ...
 $ renda    : num [1:1368] 1.45 2.41 1.93 1.45 0.48 0.96 1.2 2.41 2.17 0.72 ...
 $ ig       : num [1:1368] 29 33 33 33 33 33 33 33 34 34 ...
 $ tipoParto: Factor w/ 2 levels "normal","cesareo": 2 2 1 1 2 1 2 1 1 2 ...
 $ fumo     : Factor w/ 2 levels "sim","não": 2 2 2 2 2 1 1 2 2 2 ...
 $ pesoRN   : num [1:1368] 1035 2300 1580 1840 2475 ...
 $ sexo     : Factor w/ 2 levels "masc","fem": 2 2 2 2 2 2 2 2 2 2 ...</code></pre>
</div>
</div>
<p>Se houver necessidade de se excluir alguma variável (coluna), basta colocar o sinal de subtração (-) antes do nome da variável:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>mater2 <span class="ot">&lt;-</span> <span class="fu">select</span>(mater1, <span class="sc">-</span>altura)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mater2)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [1,368 × 9] (S3: tbl_df/tbl/data.frame)
 $ idadeMae : num [1:1368] 42 29 19 31 34 29 30 34 17 32 ...
 $ peso     : num [1:1368] 69.9 78 81 74 60 60 75.5 61 57 70 ...
 $ anosEst  : num [1:1368] 3 11 9 5 7 8 4 6 10 1 ...
 $ renda    : num [1:1368] 1.45 2.41 1.93 1.45 0.48 0.96 1.2 2.41 2.17 0.72 ...
 $ ig       : num [1:1368] 29 33 33 33 33 33 33 33 34 34 ...
 $ tipoParto: Factor w/ 2 levels "normal","cesareo": 2 2 1 1 2 1 2 1 1 2 ...
 $ fumo     : Factor w/ 2 levels "sim","não": 2 2 2 2 2 1 1 2 2 2 ...
 $ pesoRN   : num [1:1368] 1035 2300 1580 1840 2475 ...
 $ sexo     : Factor w/ 2 levels "masc","fem": 2 2 2 2 2 2 2 2 2 2 ...</code></pre>
</div>
</div>
</section>
<section id="função-filter" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="função-filter"><span class="header-section-number">5.3.2</span> Função <code>filter()</code></h3>
<p>A função <code>filter()</code> é usada para criar um subconjunto de dados que obedeçam determinadas condições lógicas: &amp; (e), | (ou) e ! (não). Por exemplo:</p>
<ul>
<li><strong>y &amp; !x</strong> <span class="math inline">\(\to\)</span> seleciona <em>y</em> e não <em>x</em></li>
<li><strong>x &amp; !y</strong> <span class="math inline">\(\to\)</span> seleciona <em>x</em> e não <em>y</em></li>
<li><strong>x | !x</strong> <span class="math inline">\(\to\)</span> seleciona <em>x</em> ou <em>y</em></li>
<li><strong>x &amp; !x</strong> <span class="math inline">\(\to\)</span> seleciona <em>x</em> e <em>y</em></li>
</ul>
<p>Um recém-nascido é dito a termo quando a duração da gestação é igual a 37 a 42 semanas incompletas. Se quisermos extrair do banco de dados <code>mater1</code> os recém-nascidos a termo (<code>mater3</code>), pode-se usar a função <code>filter()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>mater3 <span class="ot">&lt;-</span> <span class="fu">filter</span> (mater1, ig<span class="sc">&gt;=</span><span class="dv">37</span> <span class="sc">&amp;</span> ig<span class="sc">&lt;</span><span class="dv">42</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Para exibir o resultado, execute a função <code>str()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mater3)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [1,085 × 10] (S3: tbl_df/tbl/data.frame)
 $ idadeMae : num [1:1085] 28 31 27 28 18 28 22 28 25 14 ...
 $ altura   : num [1:1085] 1.5 1.55 1.6 1.58 1.76 1.63 1.54 1.55 1.56 1.51 ...
 $ peso     : num [1:1085] 48.5 65 60 47 65.5 72 65 74 70 56.7 ...
 $ anosEst  : num [1:1085] 6 5 8 8 7 11 6 5 9 6 ...
 $ renda    : num [1:1085] 3.13 0.72 2.41 1.69 1.93 1.92 2.65 2.53 0.48 1.92 ...
 $ ig       : num [1:1085] 37 37 37 38 39 39 39 39 39 39 ...
 $ tipoParto: Factor w/ 2 levels "normal","cesareo": 1 2 2 1 1 2 2 1 1 1 ...
 $ fumo     : Factor w/ 2 levels "sim","não": 2 2 1 2 1 1 2 2 2 2 ...
 $ pesoRN   : num [1:1085] 3285 3100 3100 2800 3270 ...
 $ sexo     : Factor w/ 2 levels "masc","fem": 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
</div>
<p>Observe que, agora, o conjunto de dados <code>mater3</code> tem 1085 linhas, número de recém-nascidos a termo do banco de dados original <code>mater</code> (1368). Logo, os recém nascidos a termo correspondem a 79.3% dos nascimentos, nesta maternidade.</p>
<p><strong>Outro exemplo</strong></p>
<p>Para selecionar apenas os meninos, nascidos a termo, codificados como <code>"masc"</code>, procede-se da seguinte maneira<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>meninos <span class="ot">&lt;-</span> <span class="fu">filter</span> (mater3, sexo <span class="sc">==</span> <span class="st">'masc'</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(meninos)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [592 × 10] (S3: tbl_df/tbl/data.frame)
 $ idadeMae : num [1:592] 28 31 27 28 18 28 22 28 25 14 ...
 $ altura   : num [1:592] 1.5 1.55 1.6 1.58 1.76 1.63 1.54 1.55 1.56 1.51 ...
 $ peso     : num [1:592] 48.5 65 60 47 65.5 72 65 74 70 56.7 ...
 $ anosEst  : num [1:592] 6 5 8 8 7 11 6 5 9 6 ...
 $ renda    : num [1:592] 3.13 0.72 2.41 1.69 1.93 1.92 2.65 2.53 0.48 1.92 ...
 $ ig       : num [1:592] 37 37 37 38 39 39 39 39 39 39 ...
 $ tipoParto: Factor w/ 2 levels "normal","cesareo": 1 2 2 1 1 2 2 1 1 1 ...
 $ fumo     : Factor w/ 2 levels "sim","não": 2 2 1 2 1 1 2 2 2 2 ...
 $ pesoRN   : num [1:592] 3285 3100 3100 2800 3270 ...
 $ sexo     : Factor w/ 2 levels "masc","fem": 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
</div>
<p>O banco de dados <code>meninos</code> é constituídos por 592 meninos. Isto representa 43.3% dos nascimentos.</p>
<p>Uma outra maneira de se fazer a mesma coisa, é usar a função <code>grepl()</code>, dentro da função <code>filter ()</code>. Ela é usada para pesquisar a correspondência de padrões. No código a seguir, pesquisa-se os registros em que a variável <code>sexo</code> contém <code>“fem”</code>, correspondentes às meninas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>meninas <span class="ot">&lt;-</span> <span class="fu">filter</span> (mater3, <span class="fu">grepl</span>(<span class="st">"fem"</span>, sexo))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(meninas)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [493 × 10] (S3: tbl_df/tbl/data.frame)
 $ idadeMae : num [1:493] 17 30 27 28 17 21 28 19 24 43 ...
 $ altura   : num [1:493] 1.65 1.6 1.53 1.4 1.55 1.52 1.58 1.55 1.72 1.6 ...
 $ peso     : num [1:493] 60 54 43.5 60 78 52 50 60.5 60 53 ...
 $ anosEst  : num [1:493] 7 5 11 8 10 11 11 8 8 4 ...
 $ renda    : num [1:493] 1.92 1.92 1.93 2.17 4.82 0.96 4.82 1.69 0.96 1.92 ...
 $ ig       : num [1:493] 38 39 39 38 40 38 37 38 40 39 ...
 $ tipoParto: Factor w/ 2 levels "normal","cesareo": 1 2 1 1 2 1 1 1 1 1 ...
 $ fumo     : Factor w/ 2 levels "sim","não": 2 2 2 2 1 2 1 1 1 2 ...
 $ pesoRN   : num [1:493] 3165 3150 2980 3095 3020 ...
 $ sexo     : Factor w/ 2 levels "masc","fem": 2 2 2 2 2 2 2 2 2 2 ...</code></pre>
</div>
</div>
</section>
<section id="sec-mutate" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="sec-mutate"><span class="header-section-number">5.3.3</span> Função <code>mutate()</code></h3>
<p>Esta função tem a finalidade de computar ou anexar uma ou mais colunas (variáveis) novas.</p>
<p>O Índice de Massa Corporal (IMC) é igual a</p>
<p><span class="math display">\[IMC = \frac {peso}{altura ^2}\]</span>.</p>
<p>O peso deve ser expreso em kg e a altura em metros. Para acrescentar este indicador no banco de dados <code>mater1</code> , se fará uso da função <code>mutate()</code>, nomeando a nova variável de imc:</p>
<p>Será acrescentado a variável <code>imc</code>, no banco de dados <code>mater1</code>, usando a função <code>mutate()</code>, nomenando essa variável de <code>imc</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>mater1 <span class="ot">&lt;-</span> <span class="fu">mutate</span>(mater1, <span class="at">imc =</span> peso<span class="sc">/</span>altura<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span> (mater1)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [1,368 × 11] (S3: tbl_df/tbl/data.frame)
 $ idadeMae : num [1:1368] 42 29 19 31 34 29 30 34 17 32 ...
 $ altura   : num [1:1368] 1.65 1.66 1.72 1.55 1.6 1.5 1.54 1.63 1.68 1.5 ...
 $ peso     : num [1:1368] 69.9 78 81 74 60 60 75.5 61 57 70 ...
 $ anosEst  : num [1:1368] 3 11 9 5 7 8 4 6 10 1 ...
 $ renda    : num [1:1368] 1.45 2.41 1.93 1.45 0.48 0.96 1.2 2.41 2.17 0.72 ...
 $ ig       : num [1:1368] 29 33 33 33 33 33 33 33 34 34 ...
 $ tipoParto: Factor w/ 2 levels "normal","cesareo": 2 2 1 1 2 1 2 1 1 2 ...
 $ fumo     : Factor w/ 2 levels "sim","não": 2 2 2 2 2 1 1 2 2 2 ...
 $ pesoRN   : num [1:1368] 1035 2300 1580 1840 2475 ...
 $ sexo     : Factor w/ 2 levels "masc","fem": 2 2 2 2 2 2 2 2 2 2 ...
 $ imc      : num [1:1368] 25.7 28.3 27.4 30.8 23.4 ...</code></pre>
</div>
</div>
</section>
<section id="função-sample_n" class="level3" data-number="5.3.4">
<h3 data-number="5.3.4" class="anchored" data-anchor-id="função-sample_n"><span class="header-section-number">5.3.4</span> Função <code>sample_n()</code></h3>
<p>Função usada para selecionar de forma aleatória linhas de um dataframe. Acostume-se a usar a ajuda (<code>?sample_n</code>) para obter informações das funções. Os seus argumentos básicos são:</p>
<ul>
<li><strong>tbl</strong> <span class="math inline">\(\to\)</span> dataframe</li>
<li><strong>size</strong> <span class="math inline">\(\to\)</span> número de linhas para selecionar</li>
<li><strong>replace</strong> <span class="math inline">\(\to\)</span> amostra com ou sem reposição?. Padrão = FALSE</li>
</ul>
<p>Uma mostra de 20 neonatos do banco de dados meninos, pode ser selecionada, usando a função <code>sample_n</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>meninos1 <span class="ot">&lt;-</span> <span class="fu">sample_n</span>(meninos, <span class="dv">20</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Assim, selecionou-se uma amostra de 20 meninos do banco de dados de recém-nascidos a termo. Pode-se, fazer um resumo da variável peso do recém-nascido (<code>meninos1$pesoRN</code>) para ver como ela se comporta, usando a função <code>summary()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(meninos1<span class="sc">$</span>pesoRN)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   2450    2661    3122    3076    3350    4215 </code></pre>
</div>
</div>
<p>É importante mencionar que toda vez que a função <code>sample_n()</code> for executada, ela irá gerar uma amostra aleatória diferente. Em consequência não se deve esperar, por exemplo, que a média dos pesos dos recém-nascidos de amostras diferentes sejam iguais.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>meninos2 <span class="ot">&lt;-</span> <span class="fu">sample_n</span>(meninos, <span class="dv">20</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(meninos2<span class="sc">$</span>pesoRN)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   1440    2892    3130    3066    3344    3855 </code></pre>
</div>
</div>
<p>Na <a href="09-distAmostrais.html#sec-dam" class="quarto-xref"><span>Seção 9.2.2</span></a> (Distribuições Amostrais), este assunto voltará à cena.</p>
<p>A função <code>sample_n()</code> está sendo eliminada, pois será substituída por <code>slice_sample()</code> do conjunto de funções que acompanham a função <code>slice()</code>.</p>
</section>
<section id="função-slice" class="level3" data-number="5.3.5">
<h3 data-number="5.3.5" class="anchored" data-anchor-id="função-slice"><span class="header-section-number">5.3.5</span> Função <code>slice()</code></h3>
<p>Esta função é usada para selecionar um subconjunto linhas com base em seus locais inteiros. Permite selecionar, remover e duplicar linhas. Para os exemplos, será usado o conjunto de dados <code>meninos</code>, criado acima. Os argumentos básicos da função <code>slice()</code> são</p>
<ul>
<li><strong>.data</strong> <span class="math inline">\(\to\)</span> dataframe</li>
<li><strong>.by</strong> <span class="math inline">\(\to\)</span> seleciona por grupo</li>
<li><strong>n, prop</strong> <span class="math inline">\(\to\)</span> fornecer n, o número de linhas, ou prop, a proporção de linhas a serem selecionadas.</li>
</ul>
<p>Exemplpos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Selecionando a linha 10</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">slice</span>(<span class="at">.data =</span> meninos, <span class="dv">10</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 10
  idadeMae altura  peso anosEst renda    ig tipoParto fumo  pesoRN sexo 
     &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;fct&gt;     &lt;fct&gt;  &lt;dbl&gt; &lt;fct&gt;
1       14   1.51  56.7       6  1.92    39 normal    não     3200 masc </code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Selecionando varias linhas, por exemplo, de 1 a 5</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">slice</span>(<span class="at">.data =</span> meninos, <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 10
  idadeMae altura  peso anosEst renda    ig tipoParto fumo  pesoRN sexo 
     &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;fct&gt;     &lt;fct&gt;  &lt;dbl&gt; &lt;fct&gt;
1       28   1.5   48.5       6  3.13    37 normal    não     3285 masc 
2       31   1.55  65         5  0.72    37 cesareo   não     3100 masc 
3       27   1.6   60         8  2.41    37 cesareo   sim     3100 masc 
4       28   1.58  47         8  1.69    38 normal    não     2800 masc 
5       18   1.76  65.5       7  1.93    39 normal    sim     3270 masc </code></pre>
</div>
</div>
<p>É possível também selecionar linhas de acordo com determinado grupo. Como grupo, será usada a variável <code>fumo</code> que tem dois níveis (<code>sim</code> e <code>não</code>). Será selecionada uma linha de cada grupo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">slice</span>(<span class="at">.data =</span> meninos, <span class="at">.by =</span> fumo, <span class="dv">1</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 10
  idadeMae altura  peso anosEst renda    ig tipoParto fumo  pesoRN sexo 
     &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;fct&gt;     &lt;fct&gt;  &lt;dbl&gt; &lt;fct&gt;
1       28    1.5  48.5       6  3.13    37 normal    não     3285 masc 
2       27    1.6  60         8  2.41    37 cesareo   sim     3100 masc </code></pre>
</div>
</div>
<p>Para separar por grupo , é possível usar a função <code>group_by()</code>, incluída no pacote <code>dplyr</code>. A melhor solução, neste caso, para aplicar diversas funções de manipulação em um dataframe é aplicar o operador pipe: <code>%&gt;%</code>. No final desta seção, será discutido com mais detalhes este operador.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a> meninos <span class="sc">%&gt;%</span> </span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">group_by</span>(fumo) <span class="sc">%&gt;%</span> </span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>   <span class="fu">slice</span> (<span class="dv">1</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 10
# Groups:   fumo [2]
  idadeMae altura  peso anosEst renda    ig tipoParto fumo  pesoRN sexo 
     &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;fct&gt;     &lt;fct&gt;  &lt;dbl&gt; &lt;fct&gt;
1       27    1.6  60         8  2.41    37 cesareo   sim     3100 masc 
2       28    1.5  48.5       6  3.13    37 normal    não     3285 masc </code></pre>
</div>
</div>
<p>A saída desse código é a mesma vista anteriormente. A vantagem é termos escrito o código na ordem em que as funções são aplicadas. Portanto, é um código mais legível.</p>
<section id="funções-auxiliares-da-função-slice" class="level4" data-number="5.3.5.1">
<h4 data-number="5.3.5.1" class="anchored" data-anchor-id="funções-auxiliares-da-função-slice"><span class="header-section-number">5.3.5.1</span> Funções auxiliares da função slice()</h4>
<p>A função <code>slice()</code> é acompanhada por várias funções auxiliares para casos de uso comuns:</p>
<ul>
<li><code>slice_head()</code> e <code>slice_tail()</code> selecionam a primeira ou a última linha;</li>
<li><code>slice_sample()</code> seleciona linhas aleatoriamente, substitui a <code>sample_n()</code>;</li>
<li><code>slice_min()</code> e <code>slice_max()</code> selecionam linhas com valores mais altos ou mais baixos de uma variável.</li>
</ul>
<p>Por exemplo, para selecionar uma amostra aleatória de 20 meninos do conjunto de dados <code>meninos</code>, pode-se usar a função <code>slice_sample()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a> meninos3 <span class="ot">&lt;-</span> <span class="fu">slice_sample</span>(<span class="at">.data =</span> meninos, <span class="at">n =</span> <span class="dv">20</span>)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">str</span> (meninos3)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [20 × 10] (S3: tbl_df/tbl/data.frame)
 $ idadeMae : num [1:20] 20 28 20 20 25 19 31 35 20 26 ...
 $ altura   : num [1:20] 1.6 1.64 1.51 1.65 1.58 1.56 1.51 1.65 1.62 1.63 ...
 $ peso     : num [1:20] 70 91 70 60 70 65.5 48 60 50 61 ...
 $ anosEst  : num [1:20] 7 6 8 5 6 8 4 11 7 7 ...
 $ renda    : num [1:20] 0.6 1.69 2.89 2.29 1.93 1.69 1.2 2.89 1.93 3.86 ...
 $ ig       : num [1:20] 40 40 40 40 40 41 39 37 39 39 ...
 $ tipoParto: Factor w/ 2 levels "normal","cesareo": 1 1 2 1 1 1 2 1 1 1 ...
 $ fumo     : Factor w/ 2 levels "sim","não": 2 2 2 1 1 2 2 2 1 2 ...
 $ pesoRN   : num [1:20] 3320 3420 3170 2800 3190 3470 3160 3470 2700 3110 ...
 $ sexo     : Factor w/ 2 levels "masc","fem": 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
</div>
<p>Como se observa no código, o argumento <code>n</code> da função deve ser nomeado explicitamente (<code>n = 20</code>). É possível também usar o argumento <code>prop</code>, colocando a proporção de linhas que se deseja selecionar. Se o objetivo é selecionar 10% da amostra, coloca-se o argumento como <code>prop = 0.10</code>. Como o dataframe <code>meninos</code> contém 592 casos, serão selecionados 59. Além disso, a função permite selecionar por grupos com o argumento <code>by =</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>meninos4 <span class="ot">&lt;-</span> <span class="fu">slice_sample</span>(<span class="at">.data =</span> meninos, <span class="at">prop =</span> <span class="fl">0.10</span>)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span> (meninos4)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [59 × 10] (S3: tbl_df/tbl/data.frame)
 $ idadeMae : num [1:59] 19 29 30 29 20 22 34 26 31 25 ...
 $ altura   : num [1:59] 1.55 1.71 1.61 1.6 1.66 1.63 1.5 1.65 1.76 1.55 ...
 $ peso     : num [1:59] 53 87 80 55.6 62 73.8 80 90 77 53 ...
 $ anosEst  : num [1:59] 5 10 11 8 11 4 2 11 8 11 ...
 $ renda    : num [1:59] 1.81 1.92 3.61 4.82 3.13 1.92 1.69 0.96 1.69 1.92 ...
 $ ig       : num [1:59] 40 41 37 39 40 39 39 39 39 39 ...
 $ tipoParto: Factor w/ 2 levels "normal","cesareo": 1 1 2 1 2 2 1 2 2 1 ...
 $ fumo     : Factor w/ 2 levels "sim","não": 2 2 2 1 2 2 2 2 2 2 ...
 $ pesoRN   : num [1:59] 3180 4660 2615 3175 3090 ...
 $ sexo     : Factor w/ 2 levels "masc","fem": 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
</div>
<p>Para maiores informações em relação a estas funções consulte a ajuda (<code>?slice()</code>).</p>
</section>
</section>
<section id="função-arrange" class="level3" data-number="5.3.6">
<h3 data-number="5.3.6" class="anchored" data-anchor-id="função-arrange"><span class="header-section-number">5.3.6</span> Função <code>arrange()</code></h3>
<p>Ordena as linhas pelos valores de uma coluna de forma ascendente ou descentente.</p>
<p>Voltando a amostra <code>meninos1</code>, será colocado em ordem crescente a variável <code>pesoRN</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(meninos1, pesoRN)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 10
   idadeMae altura  peso anosEst renda    ig tipoParto fumo  pesoRN sexo 
      &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;fct&gt;     &lt;fct&gt;  &lt;dbl&gt; &lt;fct&gt;
 1       17   1.62  74         7  1.2     41 normal    não     2450 masc 
 2       20   1.65  40         4  0.96    39 cesareo   sim     2470 masc 
 3       19   1.53  53        11 10.7     40 normal    não     2590 masc 
 4       18   1.48  60         7  1.45    40 cesareo   não     2605 masc 
 5       24   1.55  45         7  1.69    39 normal    não     2620 masc 
 6       19   1.6   58         8  1.69    39 normal    sim     2675 masc 
 7       28   1.55  53        11  2.41    37 normal    sim     2740 masc 
 8       25   1.54  54         3  1.45    37 cesareo   não     2805 masc 
 9       20   1.64  68.5       6  1.69    38 normal    não     2850 masc 
10       18   1.52  54         9  3.61    38 normal    não     3100 masc 
11       26   1.65  90        11  0.96    39 cesareo   não     3145 masc 
12       27   1.65  60         7  1.45    39 normal    sim     3170 masc 
13       30   1.58  62        11  2.89    39 normal    não     3180 masc 
14       28   1.6   54         9  2.41    38 normal    não     3265 masc 
15       25   1.62  59         7  1.93    40 cesareo   não     3340 masc 
16       30   1.56  43        11  3.61    41 normal    não     3380 masc 
17       16   1.75  60         7  1.92    39 normal    não     3490 masc 
18       37   1.7   70        11  2.89    40 cesareo   não     3650 masc 
19       36   1.54  65        11  2.89    40 cesareo   não     3790 masc 
20       27   1.57  60         9  3.61    39 cesareo   não     4215 masc </code></pre>
</div>
</div>
<p>Para a ordem decrescente, colocar a função <code>desc()</code>, dentro da função <code>arrange()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(meninos1, <span class="fu">desc</span>(pesoRN))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 10
   idadeMae altura  peso anosEst renda    ig tipoParto fumo  pesoRN sexo 
      &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;fct&gt;     &lt;fct&gt;  &lt;dbl&gt; &lt;fct&gt;
 1       27   1.57  60         9  3.61    39 cesareo   não     4215 masc 
 2       36   1.54  65        11  2.89    40 cesareo   não     3790 masc 
 3       37   1.7   70        11  2.89    40 cesareo   não     3650 masc 
 4       16   1.75  60         7  1.92    39 normal    não     3490 masc 
 5       30   1.56  43        11  3.61    41 normal    não     3380 masc 
 6       25   1.62  59         7  1.93    40 cesareo   não     3340 masc 
 7       28   1.6   54         9  2.41    38 normal    não     3265 masc 
 8       30   1.58  62        11  2.89    39 normal    não     3180 masc 
 9       27   1.65  60         7  1.45    39 normal    sim     3170 masc 
10       26   1.65  90        11  0.96    39 cesareo   não     3145 masc 
11       18   1.52  54         9  3.61    38 normal    não     3100 masc 
12       20   1.64  68.5       6  1.69    38 normal    não     2850 masc 
13       25   1.54  54         3  1.45    37 cesareo   não     2805 masc 
14       28   1.55  53        11  2.41    37 normal    sim     2740 masc 
15       19   1.6   58         8  1.69    39 normal    sim     2675 masc 
16       24   1.55  45         7  1.69    39 normal    não     2620 masc 
17       18   1.48  60         7  1.45    40 cesareo   não     2605 masc 
18       19   1.53  53        11 10.7     40 normal    não     2590 masc 
19       20   1.65  40         4  0.96    39 cesareo   sim     2470 masc 
20       17   1.62  74         7  1.2     41 normal    não     2450 masc </code></pre>
</div>
</div>
</section>
<section id="função-count" class="level3" data-number="5.3.7">
<h3 data-number="5.3.7" class="anchored" data-anchor-id="função-count"><span class="header-section-number">5.3.7</span> Função <code>count()</code></h3>
<p>Permite contar rapidamente os valores únicos de uma ou mais variáveis. Esta função tem os seguintes argumentos:</p>
<ul>
<li><strong>x</strong> <span class="math inline">\(\to\)</span> dataframe</li>
<li><strong>wt</strong> <span class="math inline">\(\to\)</span> pode ser NULL (padrão) ou uma variável</li>
<li><strong>sort</strong> <span class="math inline">\(\to\)</span> padrão = FALSE; se TRUE, mostrará os maiores grupos no topo</li>
<li><strong>name</strong> <span class="math inline">\(\to\)</span> O nome da nova coluna na saída; padrão = NULL</li>
</ul>
<p>Quando o argumento <code>name</code> é omitido, a função retorna <em>n</em> como nome padrão.</p>
<p>Usando o dataframe <code>mater1</code>, a função <code>count()</code> irá contar o número de parturientes fumantes, variável dicotômica <code>fumo</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">count</span>(mater1, fumo)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  fumo      n
  &lt;fct&gt; &lt;int&gt;
1 sim     301
2 não    1067</code></pre>
</div>
</div>
</section>
<section id="operador-pipe" class="level3" data-number="5.3.8">
<h3 data-number="5.3.8" class="anchored" data-anchor-id="operador-pipe"><span class="header-section-number">5.3.8</span> Operador pipe %&gt;%</h3>
<p>O operador pipe <code>%&gt;%</code> pode ser usado para inserir um valor ou um objeto no primeiro argumento de uma função. Ele pode ser acionado digitando <code>%&gt;%</code> ou usando o atalho <code>ctrl + shift + M</code>. Em vez de passar o argumento para a função separadamente, é possível escrever o valor ou objeto e, em seguida, usar o <code>pipe</code> para convertê-lo como o argumento da função na mesma linha. Funciona como se o <code>pipe</code> jogasse o objeto dentro da função seguinte.</p>
<p>Vários comando foram utilizados, manipulando o banco de dados <code>mater.</code> Alguns procedimentos, serão mostrados, usando, agora, o operador pipe.</p>
<p>Em primeiro lugar, serão selecionadas algumas colunas do dataframe <code>mater</code>; adicionada a variável <code>imc</code>; selecionado os recém-nascidos a termo do sexo masculino, que no banco de dados <code>mater</code> está codificado como 1. Tudo em um só comando!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>meusDados <span class="ot">&lt;-</span> mater <span class="sc">%&gt;%</span> </span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(idadeMae, altura, peso, anosEst, renda, </span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>         ig, tipoParto, fumo, pesoRN, sexo) <span class="sc">%&gt;%</span> </span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">imc =</span> peso<span class="sc">/</span>altura<span class="sc">^</span><span class="dv">2</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span> (ig<span class="sc">&gt;=</span><span class="dv">37</span> <span class="sc">&amp;</span> ig<span class="sc">&lt;</span><span class="dv">42</span>, sexo <span class="sc">==</span> <span class="dv">1</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(meusDados)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [592 × 11] (S3: tbl_df/tbl/data.frame)
 $ idadeMae : num [1:592] 28 31 27 28 18 28 22 28 25 14 ...
 $ altura   : num [1:592] 1.5 1.55 1.6 1.58 1.76 1.63 1.54 1.55 1.56 1.51 ...
 $ peso     : num [1:592] 48.5 65 60 47 65.5 72 65 74 70 56.7 ...
 $ anosEst  : num [1:592] 6 5 8 8 7 11 6 5 9 6 ...
 $ renda    : num [1:592] 3.13 0.72 2.41 1.69 1.93 1.92 2.65 2.53 0.48 1.92 ...
 $ ig       : num [1:592] 37 37 37 38 39 39 39 39 39 39 ...
 $ tipoParto: num [1:592] 1 2 2 1 1 2 2 1 1 1 ...
 $ fumo     : num [1:592] 2 2 1 2 1 1 2 2 2 2 ...
 $ pesoRN   : num [1:592] 3285 3100 3100 2800 3270 ...
 $ sexo     : num [1:592] 1 1 1 1 1 1 1 1 1 1 ...
 $ imc      : num [1:592] 21.6 27.1 23.4 18.8 21.1 ...</code></pre>
</div>
</div>
<p>Observe que o dataframe <code>mater</code> aparece apenas no início e, como ele é um argumento das outras funções, ele é transferido, automaticamente, não havendo necessidade de escrever dentro na função.</p>
<p>No final, retornará um novo dataframe que foi colocado em um objeto, denominado <code>meuDados</code>, o qual contém informações de todos os 592 meninos, nascidos a termo e de suas mães.</p>
</section>
</section>
<section id="manipulação-de-datas" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="manipulação-de-datas"><span class="header-section-number">5.4</span> Manipulação de datas</h2>
<p>Originalmente, todos os que trabalham com o <em>R</em> queixavam-se de como era frustrante trabalhar com datas. Era um processo que causava grande perda de tempo nas análises. O pacote <code>lubridate</code> <span class="citation" data-cites="grolemund2011dates">(<a href="references.html#ref-grolemund2011dates" role="doc-biblioref">6</a>)</span> foi criado para simplificar ao máximo a leitura de datas e extração de informações das mesmas.<br>
Quando o <code>lubridate</code> é carregado aparece uma mensagem, avisando que alguns nomes de funções também estão contidas no pacote base do R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Anexando pacote: 'lubridate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Os seguintes objetos são mascarados por 'package:base':

    date, intersect, setdiff, union</code></pre>
</div>
</div>
<p>Para evitar confusões e verificar que as funções corretas estão sendo usadas, usa-se o duplo dois pontos (<code>::</code>) antes do nome da função, precedido do nome do pacote, por exemplo: <code>lubridate::date()</code>.</p>
<p>Para obter a data atual ou a data-hora, você pode usar as funções <code>today()</code><a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> ou <code>now()</code><a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">today</span>() </span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2025-06-17"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">now</span>()</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2025-06-17 17:46:01 -03"</code></pre>
</div>
</div>
<section id="convertendo-strings-ou-caractere-para-data" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="convertendo-strings-ou-caractere-para-data"><span class="header-section-number">5.4.1</span> Convertendo <em>strings</em> ou caractere para data</h3>
<p>Para converter <em>string</em> ou caracteres em datas, basta executar funções específicas adequadas aos dados. Elas determinam automaticamente o formato quando você especifica a ordem do componente. Para usá-los, identifique a ordem em que o ano, o mês e o dia aparecem em suas datas e, em seguida, organize “y”, “m” e “d” na mesma ordem. Isso lhe dá o nome da função do <code>lubridate</code> que analisará a data. Por exemplo, suponhamos a data de 25/12/2022:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>natal <span class="ot">&lt;-</span> <span class="st">"25/12/2022"</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>natal</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "25/12/2022"</code></pre>
</div>
</div>
<p>Aparentemente, o <em>R</em> aceitou a informação como uma data. Entretanto, se for verificada a classe do objeto, tem-se:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(natal)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "character"</code></pre>
</div>
</div>
<p>Estando como caractere, esta data não poderá ser usada em operações com datas, pois necessitaria estar como uma classe <code>date</code>. Para converte-la em data, usa-se a função <code>dmy()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>natal <span class="ot">&lt;-</span> <span class="fu">dmy</span>(natal)</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>natal</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2022-12-25"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(natal)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Date"</code></pre>
</div>
</div>
<p>Dessa forma, a data, agora está sendo reconhecida pelo <em>R</em> como <code>date</code>. É sempre importante verificar a classe da data.</p>
<p>Às vezes, as datas escritas estão com o mês abreviado, como 25/dez/2022. O procedimento é o mesmo</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>minha.data <span class="ot">&lt;-</span> <span class="st">"25/dez/2022"</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span> (minha.data)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "character"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>minha.data <span class="ot">&lt;-</span> <span class="fu">dmy</span>(minha.data)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span> (minha.data)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Date"</code></pre>
</div>
</div>
<p>Se além da data, houver necessidade de especificar o horário, basta usar <code>dmy_h()</code>, <code>dmy_hm()</code> e <code>dmy_hms()</code>. No padrão americano, pode ser usado <code>ymd()</code>.</p>
<p>O <code>lubridate</code> traz diversas funções para extrair os componentes de um objeto da classe date.</p>
<ul>
<li><code>second()</code> <span class="math inline">\(\rightarrow\)</span> extrai os segundos.</li>
<li><code>minute()</code> <span class="math inline">\(\rightarrow\)</span> extrai os minutos.</li>
<li><code>hour()</code> <span class="math inline">\(\rightarrow\)</span> extrai a hora.</li>
<li><code>wday()</code> <span class="math inline">\(\rightarrow\)</span> extrai o dia da semana.</li>
<li><code>mday()</code> <span class="math inline">\(\rightarrow\)</span> extrai o dia do mês.</li>
<li><code>month()</code> <span class="math inline">\(\rightarrow\)</span> extrai o mês.</li>
<li><code>year()</code> <span class="math inline">\(\rightarrow\)</span> extrai o ano.</li>
</ul>
<p>Por exemplo, usando a data de nascimento (<code>dn</code>) de um dos netos do autor:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>dn <span class="ot">&lt;-</span> <span class="fu">dmy</span>(<span class="st">"06/06/2018"</span>)</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="fu">year</span>(dn)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2018</code></pre>
</div>
</div>
<p>Para acrescentar um horário ao objeto data de nascimento (<code>dn</code>)^[UTC = Coordinated Universal Time}:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hour</span>(dn) <span class="ot">&lt;-</span> <span class="dv">18</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>dn</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2018-06-06 18:00:00 UTC"</code></pre>
</div>
</div>
</section>
<section id="juntando-componentes-de-datas" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="juntando-componentes-de-datas"><span class="header-section-number">5.4.2</span> Juntando componentes de datas</h3>
<p>Para juntar componentes de datas e horas, pode-se utilizar as funções <code>make_date()</code> e <code>make_datetime()</code>. Em muitos arquivos, os componentes da data estão em colunas diferentes e há necessidade de juntá-los em uma única coluna para compor a data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>felix <span class="ot">&lt;-</span> <span class="fu">make_date</span>(<span class="at">year =</span> <span class="dv">2018</span>, <span class="at">month =</span> <span class="dv">06</span>, <span class="at">day =</span> <span class="dv">06</span>)</span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>felix</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2018-06-06"</code></pre>
</div>
</div>
<p>Para juntar ano, mês, dia, hora e minuto:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>minha.data <span class="ot">&lt;-</span> <span class="fu">make_datetime</span>(<span class="at">year =</span> <span class="dv">2018</span>, </span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>                            <span class="at">month =</span> <span class="dv">06</span>, </span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">day =</span> <span class="dv">06</span>, </span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">hour =</span> <span class="dv">18</span> ,</span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a>                            <span class="at">min =</span> <span class="dv">00</span>, </span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a>                            <span class="at">sec =</span> <span class="dv">15</span>)</span>
<span id="cb93-7"><a href="#cb93-7" aria-hidden="true" tabindex="-1"></a>minha.data</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2018-06-06 18:00:15 UTC"</code></pre>
</div>
</div>
</section>
<section id="extraindo-componentes-de-datas" class="level3" data-number="5.4.3">
<h3 data-number="5.4.3" class="anchored" data-anchor-id="extraindo-componentes-de-datas"><span class="header-section-number">5.4.3</span> Extraindo componentes de datas</h3>
<p>Quando temos objetos do tipo POSIXt<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a> podemos extrair componentes ou elementos deles. Para isso são usadas algumas funções específicas do pacote <code>lubridate</code> como mostrado a seguir.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">now</span>()</span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a><span class="fu">year</span>(data)            <span class="co"># Extrai o ano</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2025</code></pre>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">month</span>(data)           <span class="co"># Extrai o mês</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">week</span>(data)            <span class="co"># Extrai a semana</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24</code></pre>
</div>
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">day</span>(data)             <span class="co"># Extrai o dia</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 17</code></pre>
</div>
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">minute</span>(data)          <span class="co"># Extrai o minuto</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 46</code></pre>
</div>
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">second</span>(data)          <span class="co"># Extrai o segundo</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.096568</code></pre>
</div>
</div>
<p>Para verificar o número de dias tem em um determinado mês, usa-se a função <code>days_in_month()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a> data1 <span class="ot">&lt;-</span> <span class="fu">dmy</span>(<span class="st">"25/02/2000"</span>)</span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">days_in_month</span>(data1)          </span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Feb 
 29 </code></pre>
</div>
</div>
</section>
<section id="operações-com-datas" class="level3" data-number="5.4.4">
<h3 data-number="5.4.4" class="anchored" data-anchor-id="operações-com-datas"><span class="header-section-number">5.4.4</span> Operações com datas</h3>
<p>O pacote <code>lubridate</code> possui funções de duração e de período para manipular as datas. As funções de duração calculam o número de segundos em um determinado num determinado número de dias. As funções de duração não levam em consideração anos bissextos e horário de verão, enquanto as funções de período consideram esses fatores.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ddays</span> (<span class="dv">1</span>)           <span class="co"># Número de segundos em 1 dia</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "86400s (~1 days)"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dhours</span> (<span class="dv">1</span>)          <span class="co"># Número de segundos em 1 hora</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "3600s (~1 hours)"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dminutes</span> (<span class="dv">1</span>)        <span class="co"># Número de segundos em 1 minuto</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "60s (~1 minutes)"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="fu">days</span> (<span class="dv">5</span>)            <span class="co"># Cria um período de 5 dias</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "5d 0H 0M 0S"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="fu">weeks</span> (<span class="dv">5</span>)           <span class="co"># Cria um período de 5 semanas</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "35d 0H 0M 0S"</code></pre>
</div>
</div>
<p>Suponha-se que haja necessidade de saber em qual dia cairá após acrescentarmos 5 semanas à <code>data1</code> (25/02/2000), criada acima:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a>data1 <span class="sc">+</span> <span class="fu">weeks</span> (<span class="dv">5</span>)           </span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2000-03-31"</code></pre>
</div>
</div>
<p>Adicionando 1 ano à <code>data1</code> (25/02/2000) com uma função de duração, tem-se:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a>data1 <span class="sc">+</span> <span class="fu">dyears</span> (<span class="dv">1</span>)           </span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2001-02-24 06:00:00 UTC"</code></pre>
</div>
</div>
<p>Se for adicionado um ano à mesma data, mas agora com uma função de período, tem-se:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a>data1 <span class="sc">+</span> <span class="fu">years</span> (<span class="dv">1</span>)           </span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2001-02-25"</code></pre>
</div>
</div>
<p>Um intervalo de tempo pode ser obtido a partir de uma data inicial e uma data final. Suponha que uma gestante tenha como data da sua última menstruação 04/10/2022 e o bebê tenha nascido em 30/06/2023. Qual a idade gestacional em dias? A sintaxe para calcular um intervalo é dada pela subtração das duas datas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a>data.inicial <span class="ot">&lt;-</span> <span class="fu">dmy</span>(<span class="st">"04/10/2022"</span>)</span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a>data.final <span class="ot">&lt;-</span> <span class="fu">dmy</span>(<span class="st">"30/06/2023"</span>)</span>
<span id="cb125-3"><a href="#cb125-3" aria-hidden="true" tabindex="-1"></a>idade_gesta <span class="ot">&lt;-</span> data.final <span class="sc">-</span> data.inicial</span>
<span id="cb125-4"><a href="#cb125-4" aria-hidden="true" tabindex="-1"></a>idade_gesta</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Time difference of 269 days</code></pre>
</div>
</div>
<p>Ou seja a gestação durou 269 dias, constituindo-se em um parto a termo, entre 37 (259 dias) e 42 semanas (294 dias).</p>
<p>Para mais informações sobre o <code>lubridate</code>, consulte a ajuda do pacote ou o capítulo 16 do livro <em>R for Data Science</em>, Hadley Wickman e Garrett Grolemund, 2017 [https://r4ds.had.co.nz/index.html] .</p>


<div id="refs" class="references csl-bib-body" role="list" style="display: none">
<div id="ref-wickham2019tidyverse" class="csl-entry" role="listitem">
<div class="csl-left-margin">1. </div><div class="csl-right-inline">Wickham H, Averick M, Bryan J, Chang W, et al. Welcome to the Tidyverse. Journal of Open Source Software. 2019;4(43):1686. </div>
</div>
<div id="ref-wickham2022tidyr" class="csl-entry" role="listitem">
<div class="csl-left-margin">2. </div><div class="csl-right-inline">Wickham H, Girlich M. tidyr: Tidy Messy Data [Internet]. 2022. Disponível em: <a href="https://CRAN.R-project.org/package=tidyr">https://CRAN.R-project.org/package=tidyr</a></div>
</div>
<div id="ref-wickham2014tidy" class="csl-entry" role="listitem">
<div class="csl-left-margin">3. </div><div class="csl-right-inline">Wickham H. Tidy Data. Journal of Statistical Software. 2014;59(10):11–23. </div>
</div>
<div id="ref-fisher1936use" class="csl-entry" role="listitem">
<div class="csl-left-margin">4. </div><div class="csl-right-inline">Fisher RA. The use of multiple measurements in taxonomic problems. Annals of eugenics. 1936;7(2):179–88. </div>
</div>
<div id="ref-wickham2015dplyr" class="csl-entry" role="listitem">
<div class="csl-left-margin">5. </div><div class="csl-right-inline">Wickham H, François R, Henry L, Müller K, et al. dplyr: A grammar of data manipulation. R package version 04. 2015;3:156. </div>
</div>
<div id="ref-grolemund2011dates" class="csl-entry" role="listitem">
<div class="csl-left-margin">6. </div><div class="csl-right-inline">Grolemund G, Wickham H. Dates and Times Made Easy with lubridate. Journal of Statistical Software [Internet]. 2011;40(3):1–25. Disponível em: <a href="https://www.jstatsoft.org/v40/i03/">https://www.jstatsoft.org/v40/i03/</a></div>
</div>
</div>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>A mudança do nome do dataframe de <code>dadosNeonatos</code> para <code>neonatos</code> é desnecessária. Foi realizada apenas por questões didáticas.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Observe, na saída, que a variável <code>utiNeo</code> aparece palavras com acentuação (“não”). Às vezes, ao abrir o arquivo com a função <code>read.csv2()</code>, pode acontecer de esta palavra aparecer, por exemplo, como: “n3o”. Louco, não é? Se ocorrer isso, use, após o nome do arquivo e separado por vírgula, o argumento <code>fileEncoding = “latin1”</code>. Dessa forma, o erro será corrigido.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Da mesma maneira, como acontece com a função <code>read.csv2()</code>, a função equivalente do <code>readr</code> pode retornar erro na leitura de palavras com acento. Para corrigir isso, usa-se o argumento <code>locale (encoding = "latin1")</code><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>ATENÇÃO: Volta-se a insistir, o comando para carregar o conjunto de dados somente funciona, sem colocar o caminho (<em>path</em>) completo, se tudo está sendo realizado no diretório de trabalho.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Conjunto de dados coletados na maternidade-escola do Hospital Geral de Caxias do Sul<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Lembrar que o sinal de igualdade, no R, é duplo <span class="math inline">\(=\)</span><a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Equivalente ao <code>Sys.Date()</code>que acessa a data do sistema operacional.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Equivalente ao <code>Sys.time()</code> que acessa a data e hora do sistema operacional.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>POSIXt é uma classe de objetos do R que representa datas e horas. POSIXt significa Portable Operating System Interface for Unix Time, que é um padrão para medir o tempo em segundos desde 1 de janeiro de 1970. Existem duas formas internas de implementar POSIXt: POSIXct e POSIXlt. POSIXct armazena os segundos desde a época UNIX e POSIXlt armazena uma lista de dia, mês, ano, hora, minuto, segundo, etc.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiada");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiada");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./04-ambienteR.html" class="pagination-link" aria-label="Ambiente do *R*">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Ambiente do <em>R</em></span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./06-descrevendoDados.html" class="pagination-link" aria-label="Descrevendo os dados">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Descrevendo os dados</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>