<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>14&nbsp; ANOVA de medidas repetidas – Bioestatística Usando o R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./15-correlacao-regressao.html" rel="next">
<link href="./13-anova.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-8da5b4427184b79ecddefad3d342027e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./14-anovaRep.html"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">ANOVA de medidas repetidas</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Procurar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Bioestatística Usando o R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Procurar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefácio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introdução</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-dados.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Natureza dos Dados</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-producaoDados.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Produção dos Dados</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-ambienteR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Ambiente do <em>R</em></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-manipulandoDados.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Manipulando os dados no <em>RStudio</em></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-descrevendoDados.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Descrevendo os dados</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-probabilidades.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Introdução à Teoria das Probabilidades</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-assimetria_curtose.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Assimetria e Curtose</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-distAmostrais.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Distribuições Amostrais</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-estimacao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Estimação</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-testeHipoteses.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Teste de Hipóteses</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-teste-t.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Comparação entre duas médias</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Análise de Variância</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-anovaRep.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">ANOVA de medidas repetidas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-correlacao-regressao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Correlação e Regressão</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-dadosCategoricos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Análise de Dados Categóricos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-testes-naoParametricos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Métodos não paramétricos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-epidemiologia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Estatística em Epidemiologia</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#pacotes-necessários-neste-capítulo" id="toc-pacotes-necessários-neste-capítulo" class="nav-link active" data-scroll-target="#pacotes-necessários-neste-capítulo"><span class="header-section-number">14.1</span> Pacotes necessários neste capítulo</a></li>
  <li><a href="#anova-de-medidas-repetidas-de-um-fator" id="toc-anova-de-medidas-repetidas-de-um-fator" class="nav-link" data-scroll-target="#anova-de-medidas-repetidas-de-um-fator"><span class="header-section-number">14.2</span> ANOVA de medidas repetidas de um fator</a>
  <ul class="collapse">
  <li><a href="#dados-usados-nesta-seção" id="toc-dados-usados-nesta-seção" class="nav-link" data-scroll-target="#dados-usados-nesta-seção"><span class="header-section-number">14.2.1</span> Dados usados nesta seção</a></li>
  <li><a href="#visualização-dos-dados" id="toc-visualização-dos-dados" class="nav-link" data-scroll-target="#visualização-dos-dados"><span class="header-section-number">14.2.2</span> Visualização dos dados</a></li>
  <li><a href="#sec-anova2pres" id="toc-sec-anova2pres" class="nav-link" data-scroll-target="#sec-anova2pres"><span class="header-section-number">14.2.3</span> Avaliação dos pressupostos</a></li>
  <li><a href="#cálculo-da-estatística-do-teste" id="toc-cálculo-da-estatística-do-teste" class="nav-link" data-scroll-target="#cálculo-da-estatística-do-teste"><span class="header-section-number">14.2.4</span> Cálculo da estatística do teste</a></li>
  <li><a href="#testes-post-hoc" id="toc-testes-post-hoc" class="nav-link" data-scroll-target="#testes-post-hoc"><span class="header-section-number">14.2.5</span> Testes post hoc</a></li>
  <li><a href="#relatando-os-resultados-da-anova-de-medidas-repetidas-unifatorial" id="toc-relatando-os-resultados-da-anova-de-medidas-repetidas-unifatorial" class="nav-link" data-scroll-target="#relatando-os-resultados-da-anova-de-medidas-repetidas-unifatorial"><span class="header-section-number">14.2.6</span> Relatando os resultados da ANOVA de medidas repetidas unifatorial</a></li>
  </ul></li>
  <li><a href="#anova-de-medidas-repetidas-de-dois-fatores" id="toc-anova-de-medidas-repetidas-de-dois-fatores" class="nav-link" data-scroll-target="#anova-de-medidas-repetidas-de-dois-fatores"><span class="header-section-number">14.3</span> ANOVA de medidas repetidas de dois fatores</a>
  <ul class="collapse">
  <li><a href="#dados-usados-nesta-seção-1" id="toc-dados-usados-nesta-seção-1" class="nav-link" data-scroll-target="#dados-usados-nesta-seção-1"><span class="header-section-number">14.3.1</span> Dados usados nesta seção</a></li>
  <li><a href="#avaliação-dos-pressupostos" id="toc-avaliação-dos-pressupostos" class="nav-link" data-scroll-target="#avaliação-dos-pressupostos"><span class="header-section-number">14.3.2</span> Avaliação dos pressupostos</a></li>
  <li><a href="#cálculo-da-estatística-do-teste-1" id="toc-cálculo-da-estatística-do-teste-1" class="nav-link" data-scroll-target="#cálculo-da-estatística-do-teste-1"><span class="header-section-number">14.3.3</span> Cálculo da estatística do teste</a></li>
  <li><a href="#teste-post-hoc" id="toc-teste-post-hoc" class="nav-link" data-scroll-target="#teste-post-hoc"><span class="header-section-number">14.3.4</span> Teste post hoc</a></li>
  <li><a href="#relatando-os-resultados-da-anova-de-medidas-repetidas-de-dois-fatores" id="toc-relatando-os-resultados-da-anova-de-medidas-repetidas-de-dois-fatores" class="nav-link" data-scroll-target="#relatando-os-resultados-da-anova-de-medidas-repetidas-de-dois-fatores"><span class="header-section-number">14.3.5</span> Relatando os resultados da ANOVA de medidas repetidas de dois fatores</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">ANOVA de medidas repetidas</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="pacotes-necessários-neste-capítulo" class="level2" data-number="14.1">
<h2 data-number="14.1" class="anchored" data-anchor-id="pacotes-necessários-neste-capítulo"><span class="header-section-number">14.1</span> Pacotes necessários neste capítulo</h2>
<p>Instalar e carregar os seguintes pacotes:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(dplyr, </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>               ggplot2, </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>               ggpubr, </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>               ggsci,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>               knitr,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>               kableExtra,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>               readxl, </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>               rstatix, </span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>               tidyr)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="anova-de-medidas-repetidas-de-um-fator" class="level2" data-number="14.2">
<h2 data-number="14.2" class="anchored" data-anchor-id="anova-de-medidas-repetidas-de-um-fator"><span class="header-section-number">14.2</span> ANOVA de medidas repetidas de um fator</h2>
<section id="dados-usados-nesta-seção" class="level3" data-number="14.2.1">
<h3 data-number="14.2.1" class="anchored" data-anchor-id="dados-usados-nesta-seção"><span class="header-section-number">14.2.1</span> Dados usados nesta seção</h3>
<p>Os dados usados como exemplo contém os escores de autoestima de 10 indivíduos em três pontos do tempo durante uma dieta específica para determinar se esta interfere na sua autoestima. A autoestima foi determinada por uma escala <span class="citation" data-cites="rosenberg2015society">(<a href="references.html#ref-rosenberg2015society" role="doc-biblioref">1</a>)</span>, <span class="citation" data-cites="dini2001ear">(<a href="references.html#ref-dini2001ear" role="doc-biblioref">2</a>)</span>, cujos resultados variam de 0 a 30 pontos. Valores entre 15 e 25 caracterizam uma autoestima muito boa; abaixo de 15 é considerada baixa autoestima.</p>
<p>Os dados podem ser obtidos <a href="https://github.com/petronioliveira/Arquivos/blob/main/dadosAutoestima.xlsx"><strong>aqui</strong></a>. Baixe no seu diretório de trabalho e carregue com a função <code>read_excel()</code> do pacote <code>readxl</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"dados/dadosAutoestima.xlsx"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="exploração-e-transformação-dos-dados" class="level4" data-number="14.2.1.1">
<h4 data-number="14.2.1.1" class="anchored" data-anchor-id="exploração-e-transformação-dos-dados"><span class="header-section-number">14.2.1.1</span> Exploração e transformação dos dados</h4>
<p>Incialmente, observa-se como os dados foram registrados, usando a função <code>head()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dados)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
     id    t1    t2    t3
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     1 12.0   15.5  21.3
2     2  7.67  20.7  18.9
3     3  9.73  13.3  29.3
4     4 10.3   14.1  25.0
5     5  8.61  11.7  19.4
6     6  6.14  16.0  20.0</code></pre>
</div>
</div>
<p>Os dados se encontram no formato amplo (a variável <code>tempo</code> está colocada em três colunas) e para realizar a ANOVA de medidas repetidas, o <em>R</em> necessita que os dados estejam no formato longo. Para fazer esta transformação será usada a função <code>pivot_longer()</code><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> do pacote <code>tidyr</code> <span class="citation" data-cites="wickham2022tidyr">(<a href="references.html#ref-wickham2022tidyr" role="doc-biblioref">3</a>)</span>. Nesta função, no argumento <code>data</code>, coloca-se o nome do conjunto de dados; em <code>cols</code>, há necessidade informar as colunas do formato amplo que serão reunidas. No argumento <code>names_to</code>, nomear a coluna que conterá as colunas unificadas e em <code>values_to</code>, especificar o nome da variável no formato longo que conterá os valores. A variável <code>id</code> e a nova variável <code>tempo</code> devem ser convertida para fatores e o novo conjunto de dados será atribuído a um objeto nomeado <code>dadosL</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>dadosL <span class="ot">&lt;-</span> dados <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(t1, t2, t3),</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">names_to =</span> <span class="st">"tempo"</span>,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">values_to =</span> <span class="st">"escores"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">convert_as_factor</span>(id, tempo)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dadosL)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  id    tempo escores
  &lt;fct&gt; &lt;fct&gt;   &lt;dbl&gt;
1 1     t1      12.0 
2 1     t2      15.5 
3 1     t3      21.3 
4 2     t1       7.67
5 2     t2      20.7 
6 2     t3      18.9 </code></pre>
</div>
</div>
</section>
<section id="sumarização-dos-dados" class="level4" data-number="14.2.1.2">
<h4 data-number="14.2.1.2" class="anchored" data-anchor-id="sumarização-dos-dados"><span class="header-section-number">14.2.1.2</span> Sumarização dos dados</h4>
<p>Calcular algumas estatísticas resumidas dos escores de autoestima por grupos (<code>tempo</code>): média e desvio padrão, usando a funções <code>group_by()</code> e <code>summarise()</code> do pacote <code>dplyr</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a> dadosL <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>   dplyr<span class="sc">::</span><span class="fu">group_by</span>(tempo) <span class="sc">%&gt;%</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>   dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>                    média <span class="ot">=</span> <span class="fu">mean</span>(escores, <span class="at">na.rm =</span><span class="cn">TRUE</span>),</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">dp =</span> <span class="fu">sd</span>(escores, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  tempo     n média    dp
  &lt;fct&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
1 t1       10  9.42  1.66
2 t2       10 14.8   2.59
3 t3       10 22.9   3.43</code></pre>
</div>
</div>
</section>
</section>
<section id="visualização-dos-dados" class="level3" data-number="14.2.2">
<h3 data-number="14.2.2" class="anchored" data-anchor-id="visualização-dos-dados"><span class="header-section-number">14.2.2</span> Visualização dos dados</h3>
<p>A visualização pode ser obtida com um conjunto de boxplots (<a href="#fig-bxpauto" class="quarto-xref">Figura&nbsp;<span>14.1</span></a>), acrescido de barras de erro. Estes gráficos permitem visualizar a variação dos escores com o tempo.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>ggpubr<span class="sc">::</span><span class="fu">ggboxplot</span> (dadosL,</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">bxp.errorbar =</span> <span class="cn">TRUE</span>,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">bxp.errorbar.width =</span> <span class="fl">0.1</span>, </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">x =</span> <span class="st">"tempo"</span>, </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">y =</span> <span class="st">"escores"</span>, </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fill =</span> <span class="st">"lightblue"</span>,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">ylab =</span> <span class="st">"Escore de Autoestima"</span>,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>                   <span class="at">xlab =</span> <span class="st">"Tempo"</span>,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>                   <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>(),</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>                   <span class="at">legend =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_grey</span>(<span class="at">start=</span><span class="fl">0.95</span>, <span class="at">end=</span><span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span> (<span class="at">text =</span> <span class="fu">element_text</span> (<span class="at">size =</span> <span class="dv">12</span>))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-bxpauto" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bxpauto-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="14-anovaRep_files/figure-html/fig-bxpauto-1.png" class="quarto-figure quarto-figure-center figure-img" style="width:70.0%;height:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bxpauto-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;14.1: Boxplots mostrando o impacto de uma dieta nos escores de autoestima.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Outra maneira de visualizar os dados é através de um gráfico de linha (<a href="#fig-lineauto" class="quarto-xref">Figura&nbsp;<span>14.2</span></a>) que mostra bem o comportamento dos escores com o tempo:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>ggpubr<span class="sc">::</span><span class="fu">ggline</span>(dadosL, </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">x =</span> <span class="st">"tempo"</span>,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">y =</span> <span class="st">"escores"</span>,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">color =</span> <span class="st">"gray60"</span>,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">add.params =</span> <span class="fu">list</span>(<span class="at">color =</span> <span class="st">"red"</span>),</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">size =</span> <span class="dv">1</span>,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">add =</span> <span class="fu">c</span>(<span class="st">"mean_ci"</span>),</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">point.size =</span> <span class="dv">2</span>,</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">point.color =</span> <span class="st">"red"</span>,</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>                <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>()) <span class="sc">+</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>   <span class="fu">ylab</span>(<span class="st">"Escore de Autoestima"</span>) <span class="sc">+</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>   <span class="fu">xlab</span>(<span class="st">"Tempo"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-lineauto" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lineauto-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="14-anovaRep_files/figure-html/fig-lineauto-1.png" class="quarto-figure quarto-figure-center figure-img" style="width:80.0%;height:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lineauto-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;14.2: Gráfico de linha mostrando o impacto de uma dieta nos escores de autoestima.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Os dados mostram que existe uma modificação da autoestima (melhora nitidamente!) à medida que o tempo passa, utilizando a dieta.</p>
</section>
<section id="sec-anova2pres" class="level3" data-number="14.2.3">
<h3 data-number="14.2.3" class="anchored" data-anchor-id="sec-anova2pres"><span class="header-section-number">14.2.3</span> Avaliação dos pressupostos</h3>
<p>A ANOVA de medidas repetidas faz as seguintes suposições sobre os dados:</p>
<ol type="1">
<li>A amostra foi selecionada aleatoriamente da população;</li>
<li>A variável dependente é normalmente distribuída na população para cada nível do fator dentro dos sujeitos;</li>
<li>Não deve e existir outliers extremos;</li>
<li>Existência de esfericidade</li>
</ol>
<section id="identificação-de-valores-atípicos" class="level4" data-number="14.2.3.1">
<h4 data-number="14.2.3.1" class="anchored" data-anchor-id="identificação-de-valores-atípicos"><span class="header-section-number">14.2.3.1</span> Identificação de valores atípicos</h4>
<p>Não deve haver valores atípicos em nenhuma célula do delineamento Isso pode ser verificado visualizando os dados nos boxplots, mostrados anteriormente, onde se observa a presença de dois <em>outliers</em>, um no t1 e outro em t2. Além disso, pode-se verificar a presença de valores atípicos, usando a função <code>identify_outliers()</code> do pacote <code>rstatix</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>dadosL <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(tempo) <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  rstatix<span class="sc">::</span><span class="fu">identify_outliers</span>(escores)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  tempo id    escores is.outlier is.extreme
  &lt;fct&gt; &lt;fct&gt;   &lt;dbl&gt; &lt;lgl&gt;      &lt;lgl&gt;     
1 t1    6        6.14 TRUE       FALSE     
2 t2    2       20.7  TRUE       FALSE     </code></pre>
</div>
</div>
<p>A saída confirma a presença de dois valores atípicos, em t1 e em t2. Entretanto, eles não são extremos, não estão afastados acima de 3 intervalos interquatis e , provavelmente, não trarão problemas, apesar da amostra ser pequena.</p>
</section>
<section id="avaliação-da-normalidade" class="level4" data-number="14.2.3.2">
<h4 data-number="14.2.3.2" class="anchored" data-anchor-id="avaliação-da-normalidade"><span class="header-section-number">14.2.3.2</span> Avaliação da normalidade</h4>
<p>Para testar a hipótese de normalidade dos dados, será utilizado o <code>teste de Shapiro-Wilk</code> através da função <code>shapiro_test ()</code>, do pacote <code>rstatix</code> e a função <code>group_by ()</code>, incluída no pacote <code>dplyr</code> ou <code>rstatix</code>, junto com o operador <code>pipe</code> (%&gt;%):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>dadosL <span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span> (tempo) <span class="sc">%&gt;%</span> </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  rstatix<span class="sc">::</span><span class="fu">shapiro_test</span>(escores)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  tempo variable statistic     p
  &lt;fct&gt; &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt;
1 t1    escores      0.967 0.859
2 t2    escores      0.876 0.117
3 t3    escores      0.923 0.380</code></pre>
</div>
</div>
<p>A saída exibe valores <em>P</em> acima de 0,05, significando que os escores de autoestima estão normalmente distribuídos em cada momento do tempo.</p>
<p>A normalidade pode também ser avaliada com um gráfico QQ (<a href="#fig-qqauto" class="quarto-xref">Figura&nbsp;<span>14.3</span></a>) para cada um dos momentos, usando a função <code>ggqqplot ()</code> do pacote <code>ggpubr</code>, consulte a vinheta do pacote para maiores detalhes. Foi utilizado também o argumento <code>faced.by</code>, que divide em painéis, organizando-os como uma grade, de acordo com o momento ( t1, t2 e t3).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>ggpubr<span class="sc">::</span><span class="fu">ggqqplot</span>(dadosL, </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">x =</span> <span class="st">"escores"</span>,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">facet.by =</span> <span class="st">"tempo"</span>,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">"tempo"</span>, </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">palette =</span> <span class="fu">get_palette</span>(<span class="st">"Dark2"</span>, <span class="dv">3</span>),</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">legend =</span> <span class="st">"none"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-qqauto" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-qqauto-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="14-anovaRep_files/figure-html/fig-qqauto-1.png" class="quarto-figure quarto-figure-center figure-img" style="width:70.0%;height:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-qqauto-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;14.3: Gráfico QQ para verificar a normalidade
</figcaption>
</figure>
</div>
</div>
</div>
<p>Observando o gráfico, como quase todos os pontos caem aproximadamente ao longo da linha de referência, pode-se assumir a normalidade dos escores em todos os momentos do tempo.</p>
</section>
<section id="sec-esfero" class="level4" data-number="14.2.3.3">
<h4 data-number="14.2.3.3" class="anchored" data-anchor-id="sec-esfero"><span class="header-section-number">14.2.3.3</span> Esfericidade</h4>
<p>A violação da suposição de esfericidade pode distorcer os cálculos de variância resultantes de um teste ANOVA de medidas repetidas mais liberal (ou seja, um aumento na taxa de erro Tipo I). Nesse caso, a ANOVA de medidas repetidas deve ser corrigida apropriadamente dependendo do grau em que a esfericidade foi violada. Na relação entre os escores, há necessidade de pressupor que exista esfericidade (<span class="math inline">\(\epsilon\)</span> - épsilon), também chamada de circularidade, grosseiramente semelhante à homocedasticidade da ANOVA de uma via. A ANOVA de medidas repetidas pressupõe que as variâncias das diferenças entre todas as combinações de condições relacionadas (ou níveis de grupo) são iguais. A melhor maneira de verificá-la é calcular as diferenças entre os pares de escores em todas as combinações dos níveis de tratamento.</p>
<p>O <em>teste de esfericidade de Mauchly</em> é usado para avaliar se a suposição de esfericidade é atendida ou não. Isso é relatado automaticamente ao usar a função <code>anova_test ()</code> do pacote <code>rstatix</code>. Se o teste resulta em um valor <em>P</em> menor do que 0,05, pode-se concluir de que há uma diferença significativa entre as variâncias das diferenças.</p>
<p>O principal problema da violação da condição de esfericidade é a ocorrência de testes <em>F</em> não exatos e liberais, com consequente perda do poder do teste. Existem várias correções que podem ser aplicadas para produzir uma razão <em>F</em> válida, através do ajuste dos graus de liberdade.</p>
<p>As correções mais frequentemente preconizadas são o <span class="math inline">\(\epsilon\)</span> de <em>Greenhouse-Geisser (GGe)</em> e o <span class="math inline">\(\epsilon\)</span> de <em>Huynh-Feldt (HFe)</em>. Huynh e Feldt <span class="citation" data-cites="huynh1976epsilon">(<a href="references.html#ref-huynh1976epsilon" role="doc-biblioref">4</a>)</span> relataram que quando a correção <span class="math inline">\(\epsilon\)</span> de Greenhouse-Geisser é &gt; 0,75 muitas hipóteses nulas falsas deixam de ser rejeitadas, isto é, o teste é muito conservador, propondo outra correção dos graus de liberdade. É recomendado o uso da correção de Greenhouse-Geisser para o ajuste dos graus de liberdade quando <span class="math inline">\(\epsilon\)</span> &lt; 0,75 ou nada se sabe a respeito da esfericidade <span class="citation" data-cites="girden1992epsilon">(<a href="references.html#ref-girden1992epsilon" role="doc-biblioref">5</a>)</span>. Avaliando o poder destes testes, Muller <span class="citation" data-cites="muller1989sphericity">(<a href="references.html#ref-muller1989sphericity" role="doc-biblioref">6</a>)</span> verificou que a correção de Greenhouse-Geisser fornece um controle adicional do erro Tipo I, enquanto o poder é maximizado.</p>
</section>
</section>
<section id="cálculo-da-estatística-do-teste" class="level3" data-number="14.2.4">
<h3 data-number="14.2.4" class="anchored" data-anchor-id="cálculo-da-estatística-do-teste"><span class="header-section-number">14.2.4</span> Cálculo da estatística do teste</h3>
<p>Como mencionado, será usada a função <code>anova_test()</code>, do pacote <code>rstatix</code>, para o cálculo da ANOVA de medidas repetidas, criando um modelo que será atribuído ao objeto <code>mod.anova</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>mod.anova <span class="ot">&lt;-</span> rstatix<span class="sc">::</span><span class="fu">anova_test</span>(<span class="at">data =</span> dadosL, </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">dv =</span> escores, </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">wid =</span> id, </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">within =</span> tempo)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>mod.anova</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ANOVA Table (type III tests)

$ANOVA
  Effect DFn DFd      F        p p&lt;.05   ges
1  tempo   2  18 55.463 2.02e-08     * 0.829

$`Mauchly's Test for Sphericity`
  Effect     W     p p&lt;.05
1  tempo 0.551 0.092      

$`Sphericity Corrections`
  Effect  GGe      DF[GG]    p[GG] p[GG]&lt;.05   HFe      DF[HF]    p[HF]
1  tempo 0.69 1.38, 12.42 2.16e-06         * 0.774 1.55, 13.94 6.04e-07
  p[HF]&lt;.05
1         *</code></pre>
</div>
</div>
<p>Em primeiro lugar, observar o Teste de Mauchly para a esfericidade. Verifica-se que o efeito do tempo tem um valor <em>P</em> = 0,092, ou seja, &gt; 0,05 e, portanto, não houve violação da esfericidade e não há necessidade de observar as correções do <span class="math inline">\(\epsilon\)</span> de Greenhouse-Geisser (GGe) ou o <span class="math inline">\(\epsilon\)</span> de Huynh-Feldt (HFe).</p>
<p>Desta forma, pode-se dizer que houve uma modificação significativa no escore de de autoestima, à medida que o tempo passou (F (2,18) = 55,5, <em>P</em> &lt; 0.0001, <span class="math inline">\(\eta^2 = 0,83\)</span>).</p>
<p>Usando a função <code>get_anova_table()</code> do pacote <code>rstatix</code> para extrair a tabela ANOVA, a correção de esfericidade Greenhouse-Geisser é aplicada automaticamente aos fatores que violam a suposição de esfericidade.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>rstatix<span class="sc">::</span><span class="fu">get_anova_table</span>(mod.anova)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ANOVA Table (type III tests)

  Effect DFn DFd      F        p p&lt;.05   ges
1  tempo   2  18 55.463 2.02e-08     * 0.829</code></pre>
</div>
</div>
<p>Onde,</p>
<ul>
<li><strong>F</strong> indica que se está comparando com uma distribuição <em>F</em> (teste <em>F</em>); (2, 18) indica os graus de liberdade no numerador (DFn) e no denominador (DFd), respectivamente; 55,5 indica o valor da estatística <em>F</em>.</li>
<li><strong>p</strong> especifica o valor <em>P</em>.</li>
<li><strong>ges</strong> é o tamanho do efeito generalizado (quantidade de variabilidade devido ao fator dentro dos assuntos), eta ao quadrado <span class="math inline">\(\eta^2\)</span>.</li>
</ul>
</section>
<section id="testes-post-hoc" class="level3" data-number="14.2.5">
<h3 data-number="14.2.5" class="anchored" data-anchor-id="testes-post-hoc"><span class="header-section-number">14.2.5</span> Testes post hoc</h3>
<p>É possível fazer comparações por pares. realizando vários testes <em>t</em> pareados entre os níveis do dentro do fator (tempo), usando a função <code>pairwise_t_test()</code>, incluída no <em>R</em> base. Os valores <em>P</em> são ajustados usando o método de correção de testes múltiplos de Bonferroni.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>pwc <span class="ot">&lt;-</span> dadosL <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairwise_t_test</span>(</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    escores <span class="sc">~</span> tempo, <span class="at">paired =</span> <span class="cn">TRUE</span>,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">p.adjust.method =</span> <span class="st">"bonferroni"</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>pwc</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 10
  .y.     group1 group2    n1    n2 statistic    df         p p.adj p.adj.signif
* &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;  &lt;int&gt; &lt;int&gt;     &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;       
1 escores t1     t2        10    10     -4.97     9   7.73e-4  2e-3 **          
2 escores t1     t3        10    10    -13.2      9   3.34e-7  1e-6 ****        
3 escores t2     t3        10    10     -4.87     9   8.87e-4  3e-3 **          </code></pre>
</div>
</div>
<p>Todas as diferenças pareadas são estatisticamente significativas.</p>
</section>
<section id="relatando-os-resultados-da-anova-de-medidas-repetidas-unifatorial" class="level3" data-number="14.2.6">
<h3 data-number="14.2.6" class="anchored" data-anchor-id="relatando-os-resultados-da-anova-de-medidas-repetidas-unifatorial"><span class="header-section-number">14.2.6</span> Relatando os resultados da ANOVA de medidas repetidas unifatorial</h3>
<p>Pode-se relatar de forma simples:</p>
<ol type="1">
<li><p>Os escores de autoestima se modificaram de forma significativa de acordo com a passagem do tempo, F(2, 18) = 55,5, p &lt; 0,0001, <span class="math inline">\(\eta^2\)</span> = 0,82.</p></li>
<li><p>Análises post hoc, com um ajuste de Bonferroni, revelaram que todas as diferenças pareadas, entre os pontos de tempo, foram estatisticamente diferentes (<em>P</em> &lt; 0,05).</p></li>
</ol>
<p>Uma opção de apresentação gráfica, é o gráfico de linhas (<a href="#fig-lineauto1" class="quarto-xref">Figura&nbsp;<span>14.4</span></a>), usando a função <code>ggline()</code> do pacote <code>ggpubr</code>, junto com os teste estatísticos:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>gl <span class="ot">&lt;-</span> ggpubr<span class="sc">::</span><span class="fu">ggline</span>(dadosL,</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">x =</span> <span class="st">"tempo"</span>,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">y =</span> <span class="st">"escores"</span>,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">color =</span> <span class="st">"gray60"</span>,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">add.params =</span> <span class="fu">list</span>(<span class="at">color =</span> <span class="st">"black"</span>),</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">size =</span> <span class="fl">0.7</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>                     <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>                     <span class="at">add =</span> <span class="st">"mean_ci"</span>,</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>                     <span class="at">point.size =</span> <span class="dv">1</span>,</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>                     <span class="at">point.color =</span> <span class="st">"black"</span>)</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>gl <span class="sc">+</span> </span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>  ggpubr<span class="sc">::</span><span class="fu">stat_pvalue_manual</span>(pwc, </span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>                             <span class="at">label =</span> <span class="st">"p.adj"</span>, </span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>                             <span class="at">tip.length =</span> <span class="fl">0.00</span>,</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>                             <span class="at">y.position =</span> <span class="fu">c</span>(<span class="dv">23</span>, <span class="dv">29</span>, <span class="dv">26</span>)) <span class="sc">+</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span> (<span class="at">x =</span> <span class="st">"Tempo"</span>,</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>        <span class="at">y =</span> <span class="st">"Escore de autoestima"</span>,</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">subtitle =</span> <span class="fu">get_test_label</span> (mod.anova, <span class="at">detailed =</span> <span class="cn">TRUE</span>),</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>        <span class="at">caption =</span> <span class="fu">get_pwc_label</span>(pwc))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-lineauto1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lineauto1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="14-anovaRep_files/figure-html/fig-lineauto1-1.png" class="quarto-figure quarto-figure-center figure-img" style="width:80.0%;height:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lineauto1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;14.4: Impacto de uma dieta específica na autoestima.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="anova-de-medidas-repetidas-de-dois-fatores" class="level2" data-number="14.3">
<h2 data-number="14.3" class="anchored" data-anchor-id="anova-de-medidas-repetidas-de-dois-fatores"><span class="header-section-number">14.3</span> ANOVA de medidas repetidas de dois fatores</h2>
<section id="dados-usados-nesta-seção-1" class="level3" data-number="14.3.1">
<h3 data-number="14.3.1" class="anchored" data-anchor-id="dados-usados-nesta-seção-1"><span class="header-section-number">14.3.1</span> Dados usados nesta seção</h3>
<p>O conjunto de dados de <code>dadosAutoestima2.xlsx</code> contém as medidas dos escores de autoestima de 12 indivíduos inscritos em 2 ensaios clínicos sucessivos de curto prazo (4 semanas): placebo e dieta especial.</p>
<p>Os dados podem ser obtidos <a href="https://github.com/petronioliveira/Arquivos/blob/main/dadosAutoestima2.xlsx"><strong>aqui</strong></a>. Baixe no seu diretório de trabalho.</p>
<p>Cada participante participou dos dois ensaios. A ordem das tentativas foi equilibrada e foi permitido tempo suficiente entre os ensaios para permitir que quaisquer efeitos dos ensaios anteriores se dissipassem (<em>washout</em>).O escore de autoestima foi registrado em três momentos: no início (t1), no meio (t2) e no final (t3) dos ensaios.</p>
<p>A questão é investigar se esse tratamento dietético de curto prazo pode induzir um aumento significativo do escore de autoestima ao longo do tempo. Em outras palavras, se quer saber se há interação significativa entre dieta e tempo no escore de autoestima.</p>
<section id="leitura-dos-dados" class="level4" data-number="14.3.1.1">
<h4 data-number="14.3.1.1" class="anchored" data-anchor-id="leitura-dos-dados"><span class="header-section-number">14.3.1.1</span> Leitura dos dados</h4>
<p>A leitura dos dados será feita com a função <code>read_excel()</code> do pacote <code>readxl</code>. Após a leitura, será exibida 3 linhas aleatórias por grupo de tratamento, usando a função <code>sample_n_by()</code> do pacote <code>rstatix</code>::</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>autoestima <span class="ot">&lt;-</span> readxl<span class="sc">::</span><span class="fu">read_excel</span>(<span class="st">"dados/dadosAutoestima2.xlsx"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>autoestima <span class="sc">%&gt;%</span> <span class="fu">sample_n_by</span>(tratamento, <span class="at">size =</span> <span class="dv">3</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
     id tratamento    t1    t2    t3
  &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     3 dieta       27.3  27.3  27.6
2    12 dieta       24    24    23.4
3    10 dieta       27    27.9  28.5
4     2 placebo     29.1  28.5  26.4
5     6 placebo     21.6  19.5  18.9
6     5 placebo     23.1  21.9  20.4</code></pre>
</div>
</div>
</section>
<section id="transformação-dos-dados" class="level4" data-number="14.3.1.2">
<h4 data-number="14.3.1.2" class="anchored" data-anchor-id="transformação-dos-dados"><span class="header-section-number">14.3.1.2</span> Transformação dos dados</h4>
<p>Os dados autoestima estão no formato amplo e as colunas <code>t1</code>, <code>t2</code> e <code>t3</code> devem ser reunidas, em uma única variável denominada <code>tempo</code>, transformando o formato amplo em longo, usando a função <code>pivot_longer()</code> do pacote <code>tidyr</code>. A seguir, converter em fator esta nova variável <code>tempo</code> e a variável identificadora <code>id</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a> autoestimaL <span class="ot">&lt;-</span> autoestima <span class="sc">%&gt;%</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>   tidyr<span class="sc">::</span><span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(t1, t2, t3),</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">names_to =</span> <span class="st">"tempo"</span>,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">values_to =</span> <span class="st">"escores"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>   <span class="fu">convert_as_factor</span>(id, tratamento, tempo)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Explorar o novo conjunto de dados no formato longo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>autoestimaL <span class="sc">%&gt;%</span> <span class="fu">sample_n_by</span>(tratamento, tempo, <span class="at">size =</span> <span class="dv">1</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  id    tratamento tempo escores
  &lt;fct&gt; &lt;fct&gt;      &lt;fct&gt;   &lt;dbl&gt;
1 4     dieta      t1       27.3
2 6     dieta      t2       22.5
3 9     dieta      t3       27.9
4 10    placebo    t1       27.6
5 11    placebo    t2       27.6
6 5     placebo    t3       20.4</code></pre>
</div>
</div>
<p>Nesse exemplo, o efeito do “tempo” no escore de autoestima é nossa variável focal, nossa principal preocupação.</p>
<p>No entanto, pensa-se que o efeito “tempo” será diferente se o tratamento for realizado ou não. Nesse cenário, a variável “tratamento” é considerada como variável moderadora.</p>
</section>
<section id="sumarização-dos-dados-1" class="level4" data-number="14.3.1.3">
<h4 data-number="14.3.1.3" class="anchored" data-anchor-id="sumarização-dos-dados-1"><span class="header-section-number">14.3.1.3</span> Sumarização dos dados</h4>
<p>Os dados serão por <code>tratamento</code> e <code>tempo</code> e, em seguida, serão calculadas algumas estatísticas resumidas da variável de <code>escore</code>: média e sd (desvio padrão).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>autoestimaL <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(tratamento, tempo) <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  rstatix<span class="sc">::</span><span class="fu">get_summary_stats</span>(escores, <span class="at">type =</span> <span class="st">"mean_sd"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  tratamento tempo variable     n  mean    sd
  &lt;fct&gt;      &lt;fct&gt; &lt;fct&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 dieta      t1    escores     12  26.3  2.29
2 dieta      t2    escores     12  26.4  2.23
3 dieta      t3    escores     12  26.3  2.44
4 placebo    t1    escores     12  26.4  2.42
5 placebo    t2    escores     12  25.2  3.07
6 placebo    t3    escores     12  23.6  3.16</code></pre>
</div>
</div>
</section>
<section id="visualização-dos-dados-1" class="level4" data-number="14.3.1.4">
<h4 data-number="14.3.1.4" class="anchored" data-anchor-id="visualização-dos-dados-1"><span class="header-section-number">14.3.1.4</span> Visualização dos dados</h4>
<p>Serão criados boxplots (<a href="#fig-bxpauto1" class="quarto-xref">Figura&nbsp;<span>14.5</span></a>) do escore coloridos pelos grupos de tratamento, com cores da paleta do NEJM, usando o pacote <code>ggsci</code> e a função <code>scale_fill_nejm()</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>ggpubr<span class="sc">::</span><span class="fu">ggboxplot</span> (autoestimaL,</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">bxp.errorbar =</span> <span class="cn">TRUE</span>,</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">bxp.errorbar.width =</span> <span class="fl">0.1</span>, </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">x =</span> <span class="st">"tempo"</span>, </span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">y =</span> <span class="st">"escores"</span>, </span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fill =</span> <span class="st">"tratamento"</span>,</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">ylab =</span> <span class="st">"Escore de Autoestima"</span>,</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>                   <span class="at">xlab =</span> <span class="st">"Tempo"</span>,</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>                   <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>())<span class="sc">+</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_nejm</span>() <span class="sc">+</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span> (<span class="at">text =</span> <span class="fu">element_text</span> (<span class="at">size =</span> <span class="dv">12</span>)) </span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-bxpauto1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bxpauto1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="14-anovaRep_files/figure-html/fig-bxpauto1-1.png" class="quarto-figure quarto-figure-center figure-img" style="width:80.0%;height:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bxpauto1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;14.5: Impacto de uma dieta específica na autoestima.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="avaliação-dos-pressupostos" class="level3" data-number="14.3.2">
<h3 data-number="14.3.2" class="anchored" data-anchor-id="avaliação-dos-pressupostos"><span class="header-section-number">14.3.2</span> Avaliação dos pressupostos</h3>
<p>Os pressupostos da ANOVA de medidas repetidas de dois fatores são os mesmos da de um fator (<a href="#sec-anova2pres" class="quarto-xref"><span>Seção 14.2.3</span></a>).</p>
<section id="identificação-dos-outliers" class="level4" data-number="14.3.2.1">
<h4 data-number="14.3.2.1" class="anchored" data-anchor-id="identificação-dos-outliers"><span class="header-section-number">14.3.2.1</span> Identificação dos <em>outliers</em></h4>
<p>A observação dos boxplots mostra que não existem valores atípicos. Estes <em>outliers</em> serão analisados, usando função <code>identify_outliers()</code> do pacote <code>rstatix</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>autoestimaL <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(tratamento, tempo) <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  rstatix<span class="sc">::</span><span class="fu">identify_outliers</span>(escores)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] tratamento tempo      id         escores    is.outlier is.extreme
&lt;0 linhas&gt; (ou row.names de comprimento 0)</code></pre>
</div>
</div>
<p>A saída mostra a ausência de valores atípicos, com já se havia observado nos boxplots (<a href="#fig-bxpauto1" class="quarto-xref">Figura&nbsp;<span>14.5</span></a>).</p>
</section>
<section id="avaliação-da-normalidade-1" class="level4" data-number="14.3.2.2">
<h4 data-number="14.3.2.2" class="anchored" data-anchor-id="avaliação-da-normalidade-1"><span class="header-section-number">14.3.2.2</span> Avaliação da normalidade</h4>
<p>Para testar a hipótese de normalidade dos dados, será utilizado o <code>teste de Shapiro-Wilk</code> através da função <code>shapiro_test ()</code>, do pacote <code>rstatix</code> e a função <code>group_by ()</code>, incluída no pacote <code>dplyr</code> ou <code>rstatix</code>, junto com o operador <code>pipe</code> (%&gt;%):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>autoestimaL <span class="sc">%&gt;%</span> </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span> (tratamento, tempo) <span class="sc">%&gt;%</span> </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  rstatix<span class="sc">::</span><span class="fu">shapiro_test</span>(escores)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  tratamento tempo variable statistic      p
  &lt;fct&gt;      &lt;fct&gt; &lt;chr&gt;        &lt;dbl&gt;  &lt;dbl&gt;
1 dieta      t1    escores      0.919 0.279 
2 dieta      t2    escores      0.923 0.316 
3 dieta      t3    escores      0.886 0.104 
4 placebo    t1    escores      0.828 0.0200
5 placebo    t2    escores      0.868 0.0618
6 placebo    t3    escores      0.887 0.107 </code></pre>
</div>
</div>
<p>A saída do teste mostra que os escores de autoestima estão normalmente distribuídos em cada momento do tempo, havendo uma exceção: o grupo placebo, no momento <code>t1</code>. Fato que pode ser constatado pela assimetria do boxplot nesse momento do tempo (<a href="#fig-bxpauto1" class="quarto-xref">Figura&nbsp;<span>14.5</span></a>).</p>
<p>É possível construir um gráfico QQ (<a href="#fig-autoQQ" class="quarto-xref">Figura&nbsp;<span>14.6</span></a>) para cada um dos momentos, usando a função <code>ggqqplot ()</code> do pacote <code>ggpubr</code>, consulte a vinheta do pacote para maiores detalhes. Foi utilizado também a função <code>facet_grid()</code>, do <code>ggplot2</code>, que divide em painéis, organizando-os como uma grade, de acordo com o momento ( <code>t1</code>, <code>t2</code> e <code>t3</code>).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>ggpubr<span class="sc">::</span><span class="fu">ggqqplot</span>(<span class="at">data =</span> autoestimaL,</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">"escores"</span>, </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">color =</span> <span class="st">"tempo"</span>, </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">palette =</span> <span class="fu">get_palette</span>(<span class="st">"Dark2"</span>, <span class="dv">3</span>),</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">legend =</span> <span class="st">"none"</span>,</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>()</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>         ) <span class="sc">+</span> </span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(tempo<span class="sc">~</span>tratamento)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-autoQQ" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-autoQQ-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="14-anovaRep_files/figure-html/fig-autoQQ-1.png" class="quarto-figure quarto-figure-center figure-img" style="width:70.0%;height:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-autoQQ-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;14.6: Gráfico QQ para verificar a normalidade
</figcaption>
</figure>
</div>
</div>
</div>
<p>Observando o gráfico, como quase todos os pontos caem aproximadamente ao longo da linha de referência, pode-se seguir a análise, pois não há muito problema.</p>
</section>
<section id="esferecidade" class="level4" data-number="14.3.2.3">
<h4 data-number="14.3.2.3" class="anchored" data-anchor-id="esferecidade"><span class="header-section-number">14.3.2.3</span> Esferecidade</h4>
<p>A esferecidade será avaliada junto com a construção do modelo.</p>
</section>
</section>
<section id="cálculo-da-estatística-do-teste-1" class="level3" data-number="14.3.3">
<h3 data-number="14.3.3" class="anchored" data-anchor-id="cálculo-da-estatística-do-teste-1"><span class="header-section-number">14.3.3</span> Cálculo da estatística do teste</h3>
<p>É realizado da mesma maneira do que a ANOVA de medidas repetidas de uma via com a função <code>anova_test()</code> do pacote <code>rstatix</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>mod.anova2 <span class="ot">&lt;-</span> rstatix<span class="sc">::</span><span class="fu">anova_test</span>(<span class="at">data =</span> autoestimaL, </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">dv =</span> escores,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">wid =</span> id,</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">within =</span> tempo, </span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">between =</span> tratamento,</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">type =</span> <span class="dv">3</span>)</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>mod.anova2</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ANOVA Table (type III tests)

$ANOVA
            Effect DFn DFd      F        p p&lt;.05   ges
1       tratamento   1  22  1.432 2.44e-01       0.059
2            tempo   2  44 28.417 1.19e-08     * 0.049
3 tratamento:tempo   2  44 29.259 8.29e-09     * 0.050

$`Mauchly's Test for Sphericity`
            Effect     W     p p&lt;.05
1            tempo 0.582 0.003     *
2 tratamento:tempo 0.582 0.003     *

$`Sphericity Corrections`
            Effect   GGe      DF[GG]    p[GG] p[GG]&lt;.05   HFe      DF[HF]
1            tempo 0.705 1.41, 31.03 1.04e-06         * 0.739 1.48, 32.52
2 tratamento:tempo 0.705 1.41, 31.03 8.00e-07         * 0.739 1.48, 32.52
     p[HF] p[HF]&lt;.05
1 6.19e-07         *
2 4.72e-07         *</code></pre>
</div>
</div>
<p>Analisando o teste de Mauchly para a esfericidade, verifica-se que houve violação da esfericidade, tanto para o efeito do <code>tempo</code> (<em>W</em> = 0,582, <em>P</em> = 0,003) como para a interação <code>tratamento:tempo</code> (<em>W</em> = 0,582, <em>P</em> = 0,003). Esses resultados indicam a necessidade de correção para ajustar os graus de liberdade. A correção de Greenhouse-Geisser é utilizada, pois é o recomendado quando <em>W</em> &lt; 0,75 (veja <a href="#sec-esfero" class="quarto-xref"><span>Seção 14.2.3.3</span></a>). O modelo ANOVA, gerado pela função <code>anova_test()</code>, entregou a tabela da ANOVA sem correção, o teste de Mauchly e a correção dos graus de liberdade da esfericidade (Greenhouse-Geisser (GGe) e Huynh-Feldt (HFe)). A tabela da ANOVA corrigida (<a href="#tbl-tabanova2" class="quarto-xref">Tabela&nbsp;<span>14.1</span></a>) pode, então, ser obtida, usando a função <code>get_anova_table ()</code>, do pacote <code>rstatix</code>, com o <code>mod.anova2</code> e <code>correction = “GG”</code> como argumentos:</p>
<div class="cell">
<div id="tbl-tabanova2" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tabanova2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;14.1: Tabela da Anova Corrigida (GGe)
</figcaption>
<div aria-describedby="tbl-tabanova2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div style="border: 1px solid #ddd; padding: 5px; overflow-x: scroll; width:650px; ">
<table class="table table-striped table-hover table-condensed do-not-create-environment cell caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold;">Effect</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold;">DFn</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold;">DFd</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold;">F</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold;">p</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold;">p&lt;.05</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold;">ges</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">tratamento</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">22.00</td>
<td style="text-align: center;">1.432</td>
<td style="text-align: center;">2.44e-01</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.059</td>
</tr>
<tr class="even">
<td style="text-align: left;">tempo</td>
<td style="text-align: center;">1.41</td>
<td style="text-align: center;">31.03</td>
<td style="text-align: center;">28.417</td>
<td style="text-align: center;">1.00e-06</td>
<td style="text-align: center;">*</td>
<td style="text-align: center;">0.049</td>
</tr>
<tr class="odd">
<td style="text-align: left;">tratamento:tempo</td>
<td style="text-align: center;">1.41</td>
<td style="text-align: center;">31.03</td>
<td style="text-align: center;">29.259</td>
<td style="text-align: center;">8.00e-07</td>
<td style="text-align: center;">*</td>
<td style="text-align: center;">0.050</td>
</tr>
</tbody>
</table>
</div>

</div>
</div>
</figure>
</div>
</div>
<p>Como existe uma interação estatisticamente significativa (<em>F</em>(1,41, 31,26) = 29,6, <em>P</em> &lt; 0,0001) entre <code>tratamento</code> e o <code>tempo</code>, deve-se prestar atenção a este fato. Os efeitos principais isolados perdem a importância. Para esta análise são necessários testes posteriores.</p>
</section>
<section id="teste-post-hoc" class="level3" data-number="14.3.4">
<h3 data-number="14.3.4" class="anchored" data-anchor-id="teste-post-hoc"><span class="header-section-number">14.3.4</span> Teste post hoc</h3>
<p>Uma <em>interação significativa entre os dois fatores</em> indica que o impacto que um fator (tratamento) tem na variável desfecho (<em>escore de autoestima</em>) depende do nível do outro fator (<em>tempo</em>), e vice-versa. Assim, é possível decompor a interação entre os dois fatores significativos em:</p>
<ul>
<li><p><strong>Efeito principal simples</strong>: executar o modelo unifatorial da primeira variável (tratamento) em cada nível da segunda variável (tempo),</p></li>
<li><p><strong>Comparações simples pareadas</strong>: se o efeito principal simples for significativo, executar várias comparações pareadas para determinar quais grupos são diferentes.</p></li>
</ul>
<p>Para uma <em>interação não significativa entre os dois fatores</em>, há necessidade de determinar se tem algum <em>efeito principal</em> estatisticamente significativo da saída ANOVA.</p>
<section id="procedimento-para-uma-interação-significativa-entre-os-dois-fatores" class="level4" data-number="14.3.4.1">
<h4 data-number="14.3.4.1" class="anchored" data-anchor-id="procedimento-para-uma-interação-significativa-entre-os-dois-fatores"><span class="header-section-number">14.3.4.1</span> Procedimento para uma interação significativa entre os dois fatores</h4>
<p><strong>Efeito do tratamento</strong></p>
<p>No exemplo, será analisado o efeito do tratamento no escore de auto-estima em cada momento no tempo. Note que como o tratamento tem apenas dois níveis (dieta e placebo), o teste de ANOVA e teste <em>t</em> pareado fornecem os mesmos resultados.</p>
<p><u>Efeito do tratamento em cada ponto de tempo</u></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>tratamento <span class="ot">&lt;-</span> autoestimaL <span class="sc">%&gt;%</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(tempo) <span class="sc">%&gt;%</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  rstatix<span class="sc">::</span><span class="fu">anova_test</span>(<span class="at">dv =</span> escores, <span class="at">wid =</span> id, <span class="at">within =</span> tratamento) <span class="sc">%&gt;%</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  rstatix<span class="sc">::</span><span class="fu">get_anova_table</span>() <span class="sc">%&gt;%</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  rstatix<span class="sc">::</span><span class="fu">adjust_pvalue</span>(<span class="at">method =</span> <span class="st">"bonferroni"</span>)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>tratamento</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 9
  tempo Effect       DFn   DFd      F       p `p&lt;.05`      ges   p.adj
  &lt;fct&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;   &lt;dbl&gt;
1 t1    tratamento     1    11  0.376 0.552   ""      0.000767 1      
2 t2    tratamento     1    11  9.03  0.012   "*"     0.052    0.036  
3 t3    tratamento     1    11 30.9   0.00017 "*"     0.199    0.00051</code></pre>
</div>
</div>
<p><u>Comparações pareadas entre os grupos de tratamentos</u></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>pwc <span class="ot">&lt;-</span> autoestimaL <span class="sc">%&gt;%</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(tempo) <span class="sc">%&gt;%</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairwise_t_test</span>(escores <span class="sc">~</span> tratamento, </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">paired =</span> <span class="cn">TRUE</span>,</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">p.adjust.method =</span> <span class="st">"bonferroni"</span>)</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>pwc</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 11
  tempo .y.     group1 group2     n1    n2 statistic    df       p   p.adj
* &lt;fct&gt; &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;   &lt;int&gt; &lt;int&gt;     &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1 t1    escores dieta  placebo    12    12    -0.613    11 0.552   0.552  
2 t2    escores dieta  placebo    12    12     3.00     11 0.012   0.012  
3 t3    escores dieta  placebo    12    12     5.56     11 0.00017 0.00017
# ℹ 1 more variable: p.adj.signif &lt;chr&gt;</code></pre>
</div>
</div>
<p>Considerando o valor <em>P</em> ajustado de Bonferroni (<em>p.adj</em>), pode-se observar que o efeito principal simples do tratamento não foi significativo no ponto de tempo t1 (<em>P</em> = 1). Torna-se significativo em t2 (p = 0,036) e t3 (p = 0,00051).</p>
<p>Comparações pareadas mostram que o escore médio de autoestima foi significativamente diferente entre o grupo placebo e dieta em t2 (<em>P</em> = 0,12) e t3 (<em>P</em> = 0,00017), mas não em t1 (<em>P</em> = 0,55).</p>
<p><strong>Efeito do tempo</strong></p>
<p>Observe que também é possível realizar a mesma análise para a variável <code>tempo</code> em cada nível de tratamento. Esta análise, necessariamente, não precisa ser feita!</p>
<p><u>Efeito do tempo em cada nível de tratamento</u></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>tempo <span class="ot">&lt;-</span> autoestimaL <span class="sc">%&gt;%</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(tratamento) <span class="sc">%&gt;%</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  rstatix<span class="sc">::</span><span class="fu">anova_test</span>(<span class="at">dv =</span> escores, <span class="at">wid =</span> id, <span class="at">within =</span> tempo) <span class="sc">%&gt;%</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  rstatix<span class="sc">::</span><span class="fu">get_anova_table</span>() <span class="sc">%&gt;%</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adjust_pvalue</span>(<span class="at">method =</span> <span class="st">"bonferroni"</span>)</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>tempo</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 9
  tratamento Effect   DFn   DFd      F          p `p&lt;.05`      ges     p.adj
  &lt;fct&gt;      &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;     &lt;dbl&gt;
1 dieta      tempo      2    22  0.078 0.925      ""      0.000197 1        
2 placebo    tempo      2    22 39.7   0.00000005 "*"     0.145    0.0000001</code></pre>
</div>
</div>
<p><u>Comparações pareadas entre pontos no tempo</u></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>pwc2 <span class="ot">&lt;-</span> autoestimaL <span class="sc">%&gt;%</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(tratamento) <span class="sc">%&gt;%</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairwise_t_test</span>(escores <span class="sc">~</span> tempo, <span class="at">paired =</span> <span class="cn">TRUE</span>,</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">p.adjust.method =</span> <span class="st">"bonferroni"</span>)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>pwc2</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 11
  tratamento .y.     group1 group2    n1    n2 statistic    df         p   p.adj
* &lt;fct&gt;      &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;  &lt;int&gt; &lt;int&gt;     &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 dieta      escores t1     t2        12    12    -0.522    11 0.612     1   e+0
2 dieta      escores t1     t3        12    12    -0.102    11 0.921     1   e+0
3 dieta      escores t2     t3        12    12     0.283    11 0.782     1   e+0
4 placebo    escores t1     t2        12    12     4.53     11 0.000858  3   e-3
5 placebo    escores t1     t3        12    12     6.91     11 0.0000255 7.65e-5
6 placebo    escores t2     t3        12    12     6.49     11 0.0000449 1.35e-4
# ℹ 1 more variable: p.adj.signif &lt;chr&gt;</code></pre>
</div>
</div>
<p>Após a execução do código, verifica-se que o efeito do tempo é significativo apenas para o placebo, F(2, 22) = 39,7, p &lt; 0,0001. As comparações pareadas mostram que todas as comparações entre os pontos de tempo foram estatisticamente significativas para o placebo.</p>
</section>
<section id="procedimento-para-uma-interação-não-significativa-entre-os-dois-fatores" class="level4" data-number="14.3.4.2">
<h4 data-number="14.3.4.2" class="anchored" data-anchor-id="procedimento-para-uma-interação-não-significativa-entre-os-dois-fatores"><span class="header-section-number">14.3.4.2</span> Procedimento para uma interação não significativa entre os dois fatores</h4>
<p>Se a interação não for significativa, é preciso interpretar os efeitos principais para cada uma das duas variáveis: <code>tratamento</code> e <code>tempo</code>. Um efeito principal significativo pode ser acompanhado com comparações pareadas</p>
<p>No exemplo (consulte a <a href="#tbl-tabanova2" class="quarto-xref">Tabela&nbsp;<span>14.1</span></a>), não houve efeito principal estatisticamente significativo para o tratamento (<em>F</em>(1, 22) = 1,43, <em>P</em> = 0,244) no escore de autoestima. Entretanto, os escores foram afetados significativamente pelo <code>tempo</code> (<em>F</em>(1,41, 31,03) = 28,41, <em>P</em> &lt; 0,0001).</p>
</section>
</section>
<section id="relatando-os-resultados-da-anova-de-medidas-repetidas-de-dois-fatores" class="level3" data-number="14.3.5">
<h3 data-number="14.3.5" class="anchored" data-anchor-id="relatando-os-resultados-da-anova-de-medidas-repetidas-de-dois-fatores"><span class="header-section-number">14.3.5</span> Relatando os resultados da ANOVA de medidas repetidas de dois fatores</h3>
<p>O resultado pode ser relatado da seguinte forma:</p>
<ol type="1">
<li><p>Uma ANOVA de medidas repetidas de dois fatores foi realizada para avaliar o efeito de diferentes tratamentos dietéticos ao longo do tempo no escore de autoestima.</p></li>
<li><p>Houve uma interação estatisticamente significativa entre <code>tratamento</code> e <code>tempo</code> no escore de autoestima, <em>F</em>(1,41, 31,03) = 29,26, <em>P</em> &lt; 0,0001 (<a href="#tbl-tabanova2" class="quarto-xref">Tabela&nbsp;<span>14.1</span></a>). Por isso, o efeito da variável <code>tratamento</code> foi analisado em cada ponto de tempo. Os valores de <em>P</em> foram ajustados usando o método de correção de testes múltiplos de Bonferroni. O efeito da variável <code>tratamento</code> foi significativo em t2 (<em>P</em> = 0,036) e t3 (<em>P</em> = 0,00051), mas não no ponto de tempo t1 (<em>P</em> = 1).</p></li>
<li><p>Comparações pareadas, usando o teste <em>t</em> pareado, mostram que o escore médio de autoestima foi significativamente diferente entre os ensaios <code>placebo</code> e <code>dieta</code> nos pontos de tempo t2 (<em>P</em> = 0,012) e t3 (<em>P</em> = 0,00017), mas não em t1 (<em>P</em> = 0,55).</p></li>
</ol>
<section id="visualização-dos-resultados" class="level4" data-number="14.3.5.1">
<h4 data-number="14.3.5.1" class="anchored" data-anchor-id="visualização-dos-resultados"><span class="header-section-number">14.3.5.1</span> Visualização dos resultados</h4>
<p>Os resultados podem ser visualizados através de gráficos tipo boxplots (<a href="#fig-bxpauto2" class="quarto-xref">Figura&nbsp;<span>14.7</span></a>) ou por um gráfico de linha (<a href="#fig-lineauto2" class="quarto-xref">Figura&nbsp;<span>14.8</span></a>). Os gráficos foram construídos , usando as funções <code>ggboxplot()</code> e <code>ggline()</code> do pacote <code>ggpubr</code>. Os boxplots receberam um preenchimento em tons de cinza, bem interessante em publicações científicas; o gráfico de linha, usando o pacote <code>ggsci</code>, recebeu as cores da paleta do periódico <em>Lancet</em>.</p>
<p><u>Boxplots</u></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>bxp <span class="ot">&lt;-</span> ggpubr<span class="sc">::</span><span class="fu">ggboxplot</span> (autoestimaL,</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">bxp.errorbar =</span> <span class="cn">TRUE</span>,</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">bxp.errorbar.width =</span> <span class="fl">0.1</span>, </span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">x =</span> <span class="st">"tempo"</span>, </span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">y =</span> <span class="st">"escores"</span>, </span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>                          <span class="at">fill =</span> <span class="st">"tratamento"</span>,</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>                          <span class="at">ylab =</span> <span class="st">"Escore de Autoestima"</span>,</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>                          <span class="at">xlab =</span> <span class="st">"Tempo"</span>)<span class="sc">+</span></span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_grey</span>(<span class="at">start=</span><span class="fl">0.95</span>, <span class="at">end=</span><span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"right"</span>) <span class="sc">+</span></span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span> (<span class="at">text =</span> <span class="fu">element_text</span> (<span class="at">size =</span> <span class="dv">12</span>)) </span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a>pwc <span class="ot">&lt;-</span> pwc <span class="sc">%&gt;%</span> <span class="fu">add_xy_position</span>(<span class="at">x =</span> <span class="st">"tempo"</span>)</span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a>bxp <span class="sc">+</span> </span>
<span id="cb46-16"><a href="#cb46-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_pvalue_manual</span>(pwc, </span>
<span id="cb46-17"><a href="#cb46-17" aria-hidden="true" tabindex="-1"></a>                     <span class="at">label =</span> <span class="st">"p.adj"</span>,</span>
<span id="cb46-18"><a href="#cb46-18" aria-hidden="true" tabindex="-1"></a>                     <span class="at">tip.length =</span> <span class="fl">0.01</span>, </span>
<span id="cb46-19"><a href="#cb46-19" aria-hidden="true" tabindex="-1"></a>                     <span class="at">hide.ns =</span> <span class="cn">FALSE</span>,</span>
<span id="cb46-20"><a href="#cb46-20" aria-hidden="true" tabindex="-1"></a>                     <span class="at">y.position =</span> <span class="fu">c</span>(<span class="dv">32</span>, <span class="dv">32</span>, <span class="dv">32</span>)) <span class="sc">+</span></span>
<span id="cb46-21"><a href="#cb46-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">subtitle =</span> <span class="fu">get_test_label</span>(mod.anova2, <span class="at">detailed =</span> <span class="cn">TRUE</span>),</span>
<span id="cb46-22"><a href="#cb46-22" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="fu">get_pwc_label</span>(pwc))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-bxpauto2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bxpauto2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="14-anovaRep_files/figure-html/fig-bxpauto2-1.png" class="quarto-figure quarto-figure-center figure-img" style="width:70.0%;height:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bxpauto2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;14.7: Avaliação da autoestima no decorrer do tempo
</figcaption>
</figure>
</div>
</div>
</div>
<p><u>Gráfico de linha</u></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>ggl <span class="ot">&lt;-</span> <span class="fu">ggline</span>(</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  autoestimaL,</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="st">"tempo"</span>,</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="st">"escores"</span>,</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">color =</span> <span class="st">"tratamento"</span>,</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">palette =</span> <span class="st">"lancet"</span>,</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">size =</span> <span class="fl">0.7</span>,</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">shape =</span> <span class="dv">19</span>,</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">add =</span> <span class="st">"mean_ci"</span>,</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">error.plot =</span> <span class="st">"errorbar"</span>,</span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.2</span>),</span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">ggtheme =</span> <span class="fu">theme_pubr</span>()) <span class="sc">+</span></span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"right"</span>)</span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>ggl <span class="sc">+</span> ggpubr<span class="sc">::</span><span class="fu">stat_pvalue_manual</span>(pwc,  </span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">label =</span> <span class="st">"p.adj"</span>, </span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">tip.length =</span> <span class="fl">0.00</span>,</span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">y.position =</span> <span class="fu">c</span>(<span class="fl">28.5</span>, <span class="fl">28.5</span>, <span class="fl">28.5</span>)) <span class="sc">+</span></span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span> (<span class="at">x =</span> <span class="st">"Tempo"</span>,</span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a>        <span class="at">y =</span> <span class="st">"Escore de autoestima"</span>,</span>
<span id="cb47-22"><a href="#cb47-22" aria-hidden="true" tabindex="-1"></a>        <span class="at">subtitle =</span> <span class="fu">get_test_label</span> (mod.anova2, <span class="at">detailed =</span> <span class="cn">TRUE</span>),</span>
<span id="cb47-23"><a href="#cb47-23" aria-hidden="true" tabindex="-1"></a>        <span class="at">caption =</span> <span class="fu">get_pwc_label</span>(pwc))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-lineauto2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lineauto2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="14-anovaRep_files/figure-html/fig-lineauto2-1.png" class="quarto-figure quarto-figure-center figure-img" style="width:70.0%;height:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lineauto2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;14.8: Avaliação da autoestima no decorrer do tempo
</figcaption>
</figure>
</div>
</div>
</div>


<div id="refs" class="references csl-bib-body" role="list" style="display: none">
<div id="ref-rosenberg2015society" class="csl-entry" role="listitem">
<div class="csl-left-margin">1. </div><div class="csl-right-inline">Rosenberg M. Society and the adolescent self-image. Princeton university press; 2015. </div>
</div>
<div id="ref-dini2001ear" class="csl-entry" role="listitem">
<div class="csl-left-margin">2. </div><div class="csl-right-inline">Dini G, Quaresma M, Ferreira L, et al. Adaptação cultural e validação da versão brasileira da escala de autoestima de Rosenberg. Revista Brasileira de Cirurgia Plástica. 2001;19(1):41–52. </div>
</div>
<div id="ref-wickham2022tidyr" class="csl-entry" role="listitem">
<div class="csl-left-margin">3. </div><div class="csl-right-inline">Wickham H, Girlich M. tidyr: Tidy Messy Data [Internet]. 2022. Disponível em: <a href="https://CRAN.R-project.org/package=tidyr">https://CRAN.R-project.org/package=tidyr</a></div>
</div>
<div id="ref-huynh1976epsilon" class="csl-entry" role="listitem">
<div class="csl-left-margin">4. </div><div class="csl-right-inline">Huynh H, Feldt LS. Estimation of the Box correction for degrees of freedom from sample data in randomized block and split-plot designs. Journal of Educational Statistics. 1976;1(1):69–82. </div>
</div>
<div id="ref-girden1992epsilon" class="csl-entry" role="listitem">
<div class="csl-left-margin">5. </div><div class="csl-right-inline">Girden ER. Two-Factor Studies with Repeated Measures on Both Factors. Em: ANOVA: repeated measures. Sage; 1992. p. 31–40. (QASS Series; vol. 84). </div>
</div>
<div id="ref-muller1989sphericity" class="csl-entry" role="listitem">
<div class="csl-left-margin">6. </div><div class="csl-right-inline">Muller KE, Barton CN. Approximate power for repeated-measures ANOVA lacking sphericity. Journal of the American Statistical Association. 1989;84(406):549–55. </div>
</div>
</div>
</section>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Veja a <a href="12-teste-t.html#sec-pivot" class="quarto-xref"><span>Seção 12.3.1.1</span></a> para mais detalhes da função.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiada");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiada");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./13-anova.html" class="pagination-link" aria-label="Análise de Variância">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Análise de Variância</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./15-correlacao-regressao.html" class="pagination-link" aria-label="Correlação e Regressão">
        <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Correlação e Regressão</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>